/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthResponseDto,
  PublicHealthResponseDto,
} from '../models/index';
import {
    HealthResponseDtoFromJSON,
    HealthResponseDtoToJSON,
    PublicHealthResponseDtoFromJSON,
    PublicHealthResponseDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class APIHealthApi extends runtime.BaseAPI {

    /**
     * Authenticated health check endpoint
     */
    async healthControllerCheckV0Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseDtoFromJSON(jsonValue));
    }

    /**
     * Authenticated health check endpoint
     */
    async healthControllerCheckV0(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponseDto> {
        const response = await this.healthControllerCheckV0Raw(initOverrides);
        return await response.value();
    }

    /**
     * Public health check endpoint
     */
    async healthControllerPublicHealthCheckV0Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicHealthResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v0/health/public`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicHealthResponseDtoFromJSON(jsonValue));
    }

    /**
     * Public health check endpoint
     */
    async healthControllerPublicHealthCheckV0(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicHealthResponseDto> {
        const response = await this.healthControllerPublicHealthCheckV0Raw(initOverrides);
        return await response.value();
    }

}
