/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCustomerDto,
  CustomerStatus,
  UpdateCustomerDto,
} from '../models/index';
import {
    CreateCustomerDtoFromJSON,
    CreateCustomerDtoToJSON,
    CustomerStatusFromJSON,
    CustomerStatusToJSON,
    UpdateCustomerDtoFromJSON,
    UpdateCustomerDtoToJSON,
} from '../models/index';

export interface CustomerControllerCreateRequest {
    createCustomerDto: CreateCustomerDto;
}

export interface CustomerControllerFindAllRequest {
    skip?: number;
    take?: number;
    status?: CustomerStatus;
    name?: string;
    email?: string;
}

export interface CustomerControllerFindOneRequest {
    id: string;
}

export interface CustomerControllerUpdateRequest {
    id: string;
    updateCustomerDto: UpdateCustomerDto;
}

/**
 * 
 */
export class CustomersApi extends runtime.BaseAPI {

    /**
     * Creates a new customer in the system with their personal and contact information.      This endpoint allows you to register new customers and store their details for future transactions.  ## Use Cases - Register new customers for payment processing - Store customer information for recurring payments - Maintain customer profiles for transaction history  ## Example: Create New Customer ```json {   \"first_name\": \"John\",   \"last_name\": \"Doe\",   \"email\": \"john.doe@example.com\",   \"phone_number\": \"+1-555-123-4567\",   \"customer_type\": \"Startup\",   \"status\": \"ACTIVE\" } ```  ## Required Fields - `first_name`: Customer\'s first name (1-100 characters) - `last_name`: Customer\'s last name (1-100 characters) - `phone_number`: Customer\'s phone number (max 20 characters)  ## Optional Fields - `email`: Valid email address (max 255 characters) - `customer_type`: Type of customer account (Individual, Startup, Small Business, Medium Business, Enterprise, Non-Profit, Government) - `status`: Customer status (ACTIVE, BLACKLISTED, DEACTIVATED)
     * Create a new customer
     */
    async customerControllerCreateRaw(requestParameters: CustomerControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createCustomerDto'] == null) {
            throw new runtime.RequiredError(
                'createCustomerDto',
                'Required parameter "createCustomerDto" was null or undefined when calling customerControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/customers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomerDtoToJSON(requestParameters['createCustomerDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new customer in the system with their personal and contact information.      This endpoint allows you to register new customers and store their details for future transactions.  ## Use Cases - Register new customers for payment processing - Store customer information for recurring payments - Maintain customer profiles for transaction history  ## Example: Create New Customer ```json {   \"first_name\": \"John\",   \"last_name\": \"Doe\",   \"email\": \"john.doe@example.com\",   \"phone_number\": \"+1-555-123-4567\",   \"customer_type\": \"Startup\",   \"status\": \"ACTIVE\" } ```  ## Required Fields - `first_name`: Customer\'s first name (1-100 characters) - `last_name`: Customer\'s last name (1-100 characters) - `phone_number`: Customer\'s phone number (max 20 characters)  ## Optional Fields - `email`: Valid email address (max 255 characters) - `customer_type`: Type of customer account (Individual, Startup, Small Business, Medium Business, Enterprise, Non-Profit, Government) - `status`: Customer status (ACTIVE, BLACKLISTED, DEACTIVATED)
     * Create a new customer
     */
    async customerControllerCreate(requestParameters: CustomerControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.customerControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a list of customers with optional filtering and pagination.      This endpoint allows you to search and filter customers based on various criteria.  ## Use Cases - List all customers with pagination - Search customers by name or email - Filter customers by status - Export customer data  ## Query Parameters - `skip`: Number of records to skip (default: 0, min: 0) - `take`: Number of records to take (default: 10, min: 1, max: 100) - `status`: Filter by customer status (ACTIVE, BLACKLISTED, DEACTIVATED) - `name`: Filter by customer name (partial match, case-insensitive) - `email`: Filter by customer email (exact match, case-insensitive)  ## Example Request `GET /api/v0/customers?skip=0&take=20&status=ACTIVE&name=John`  ## Example Response ```json {   \"data\": [     {       \"id\": \"cust_123456\",       \"first_name\": \"John\",       \"last_name\": \"Doe\",       \"email\": \"john.doe@example.com\",       \"phone_number\": \"+1-555-123-4567\",       \"customer_type\": \"Startup\",       \"status\": \"ACTIVE\",       \"created_at\": \"2024-03-20T10:00:00Z\",       \"updated_at\": \"2024-03-20T10:00:00Z\"     }   ],   \"total\": 100,   \"skip\": 0,   \"take\": 10 } ```
     * Get all customers with filters
     */
    async customerControllerFindAllRaw(requestParameters: CustomerControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/customers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves a list of customers with optional filtering and pagination.      This endpoint allows you to search and filter customers based on various criteria.  ## Use Cases - List all customers with pagination - Search customers by name or email - Filter customers by status - Export customer data  ## Query Parameters - `skip`: Number of records to skip (default: 0, min: 0) - `take`: Number of records to take (default: 10, min: 1, max: 100) - `status`: Filter by customer status (ACTIVE, BLACKLISTED, DEACTIVATED) - `name`: Filter by customer name (partial match, case-insensitive) - `email`: Filter by customer email (exact match, case-insensitive)  ## Example Request `GET /api/v0/customers?skip=0&take=20&status=ACTIVE&name=John`  ## Example Response ```json {   \"data\": [     {       \"id\": \"cust_123456\",       \"first_name\": \"John\",       \"last_name\": \"Doe\",       \"email\": \"john.doe@example.com\",       \"phone_number\": \"+1-555-123-4567\",       \"customer_type\": \"Startup\",       \"status\": \"ACTIVE\",       \"created_at\": \"2024-03-20T10:00:00Z\",       \"updated_at\": \"2024-03-20T10:00:00Z\"     }   ],   \"total\": 100,   \"skip\": 0,   \"take\": 10 } ```
     * Get all customers with filters
     */
    async customerControllerFindAll(requestParameters: CustomerControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.customerControllerFindAllRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves detailed information about a specific customer.      This endpoint allows you to fetch complete customer details including their contact information and status.  ## Use Cases - View customer details - Verify customer information - Check customer status before processing payments  ## Path Parameters - `id`: Customer UUID (required) - Must be a valid UUID format  ## Example Request `GET /api/v0/customers/123e4567-e89b-12d3-a456-426614174000`  ## Example Response ```json {   \"id\": \"cust_123456\",   \"first_name\": \"John\",   \"last_name\": \"Doe\",   \"email\": \"john.doe@example.com\",   \"phone_number\": \"+1-555-123-4567\",   \"customer_type\": \"Enterprise\",   \"status\": \"ACTIVE\",   \"last_spent\": 1250.50,   \"last_purchase_date\": \"2024-03-15T14:30:00Z\",   \"created_at\": \"2024-03-20T10:00:00Z\",   \"updated_at\": \"2024-03-20T10:00:00Z\" } ```
     * Get a customer by ID
     */
    async customerControllerFindOneRaw(requestParameters: CustomerControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling customerControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/customers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves detailed information about a specific customer.      This endpoint allows you to fetch complete customer details including their contact information and status.  ## Use Cases - View customer details - Verify customer information - Check customer status before processing payments  ## Path Parameters - `id`: Customer UUID (required) - Must be a valid UUID format  ## Example Request `GET /api/v0/customers/123e4567-e89b-12d3-a456-426614174000`  ## Example Response ```json {   \"id\": \"cust_123456\",   \"first_name\": \"John\",   \"last_name\": \"Doe\",   \"email\": \"john.doe@example.com\",   \"phone_number\": \"+1-555-123-4567\",   \"customer_type\": \"Enterprise\",   \"status\": \"ACTIVE\",   \"last_spent\": 1250.50,   \"last_purchase_date\": \"2024-03-15T14:30:00Z\",   \"created_at\": \"2024-03-20T10:00:00Z\",   \"updated_at\": \"2024-03-20T10:00:00Z\" } ```
     * Get a customer by ID
     */
    async customerControllerFindOne(requestParameters: CustomerControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.customerControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Updates an existing customer\'s information.      This endpoint allows you to modify customer details while preserving their core information.  ## Use Cases - Update customer contact information - Change customer type - Modify customer status  ## Path Parameters - `id`: Customer UUID (required) - Must be a valid UUID format  ## Example Request `PATCH /api/v0/customers/123e4567-e89b-12d3-a456-426614174000`  ## Example Request Body ```json {   \"first_name\": \"John\",   \"last_name\": \"Smith\",   \"phone_number\": \"+1-987-654-3210\",   \"customer_type\": \"Small Business\" } ```  ## Notes - Only include fields that need to be updated - All fields are optional in updates - Status changes may require additional verification
     * Update a customer
     */
    async customerControllerUpdateRaw(requestParameters: CustomerControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling customerControllerUpdate().'
            );
        }

        if (requestParameters['updateCustomerDto'] == null) {
            throw new runtime.RequiredError(
                'updateCustomerDto',
                'Required parameter "updateCustomerDto" was null or undefined when calling customerControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/customers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCustomerDtoToJSON(requestParameters['updateCustomerDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates an existing customer\'s information.      This endpoint allows you to modify customer details while preserving their core information.  ## Use Cases - Update customer contact information - Change customer type - Modify customer status  ## Path Parameters - `id`: Customer UUID (required) - Must be a valid UUID format  ## Example Request `PATCH /api/v0/customers/123e4567-e89b-12d3-a456-426614174000`  ## Example Request Body ```json {   \"first_name\": \"John\",   \"last_name\": \"Smith\",   \"phone_number\": \"+1-987-654-3210\",   \"customer_type\": \"Small Business\" } ```  ## Notes - Only include fields that need to be updated - All fields are optional in updates - Status changes may require additional verification
     * Update a customer
     */
    async customerControllerUpdate(requestParameters: CustomerControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.customerControllerUpdateRaw(requestParameters, initOverrides);
    }

}
