/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateLiquidationAddressDto,
  LiquidationAddressResponseDto,
} from '../models/index';
import {
    CreateLiquidationAddressDtoFromJSON,
    CreateLiquidationAddressDtoToJSON,
    LiquidationAddressResponseDtoFromJSON,
    LiquidationAddressResponseDtoToJSON,
} from '../models/index';

export interface LiquidationAddressControllerCreateLiquidationAddressRequest {
    customerId: string;
    createLiquidationAddressDto: CreateLiquidationAddressDto;
}

export interface LiquidationAddressControllerGetLiquidationAddressRequest {
    customerId: string;
    liquidationAddressId: string;
}

export interface LiquidationAddressControllerGetLiquidationAddressesRequest {
    customerId: string;
}

/**
 * 
 */
export class LiquidationAddressesApi extends runtime.BaseAPI {

    /**
     *        Create a new liquidation address for a customer. Liquidation addresses allow        customers to automatically liquidate cryptocurrency holdings to fiat or other        stablecoins based on configured parameters.        **Required fields:**       - chain: Blockchain network (ethereum, polygon, arbitrum, base)       - currency: Stablecoin currency (usdc, eurc, dai, pyusd, usdt)       - address: Valid blockchain address        **At least one destination must be specified:**       - external_account_id: External bank account       - prefunded_account_id: Developer\'s prefunded account       - bridge_wallet_id: Bridge wallet       - destination_address: Crypto wallet address        **Payment Rails:**       Different payment rails have different requirements:       - ACH: Requires external_account_id, supports destination_ach_reference       - SEPA: Requires external_account_id, supports destination_sepa_reference       - Wire: Requires external_account_id, supports destination_wire_message       - Crypto: Requires destination_address, supports destination_blockchain_memo     
     * Create a new liquidation address for a customer
     */
    async liquidationAddressControllerCreateLiquidationAddressRaw(requestParameters: LiquidationAddressControllerCreateLiquidationAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LiquidationAddressResponseDto>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling liquidationAddressControllerCreateLiquidationAddress().'
            );
        }

        if (requestParameters['createLiquidationAddressDto'] == null) {
            throw new runtime.RequiredError(
                'createLiquidationAddressDto',
                'Required parameter "createLiquidationAddressDto" was null or undefined when calling liquidationAddressControllerCreateLiquidationAddress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v0/customers/{customerId}/liquidation_addresses`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLiquidationAddressDtoToJSON(requestParameters['createLiquidationAddressDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LiquidationAddressResponseDtoFromJSON(jsonValue));
    }

    /**
     *        Create a new liquidation address for a customer. Liquidation addresses allow        customers to automatically liquidate cryptocurrency holdings to fiat or other        stablecoins based on configured parameters.        **Required fields:**       - chain: Blockchain network (ethereum, polygon, arbitrum, base)       - currency: Stablecoin currency (usdc, eurc, dai, pyusd, usdt)       - address: Valid blockchain address        **At least one destination must be specified:**       - external_account_id: External bank account       - prefunded_account_id: Developer\'s prefunded account       - bridge_wallet_id: Bridge wallet       - destination_address: Crypto wallet address        **Payment Rails:**       Different payment rails have different requirements:       - ACH: Requires external_account_id, supports destination_ach_reference       - SEPA: Requires external_account_id, supports destination_sepa_reference       - Wire: Requires external_account_id, supports destination_wire_message       - Crypto: Requires destination_address, supports destination_blockchain_memo     
     * Create a new liquidation address for a customer
     */
    async liquidationAddressControllerCreateLiquidationAddress(requestParameters: LiquidationAddressControllerCreateLiquidationAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LiquidationAddressResponseDto> {
        const response = await this.liquidationAddressControllerCreateLiquidationAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific liquidation address by its ID for a given customer.
     * Get a specific liquidation address
     */
    async liquidationAddressControllerGetLiquidationAddressRaw(requestParameters: LiquidationAddressControllerGetLiquidationAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LiquidationAddressResponseDto>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling liquidationAddressControllerGetLiquidationAddress().'
            );
        }

        if (requestParameters['liquidationAddressId'] == null) {
            throw new runtime.RequiredError(
                'liquidationAddressId',
                'Required parameter "liquidationAddressId" was null or undefined when calling liquidationAddressControllerGetLiquidationAddress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v0/customers/{customerId}/liquidation_addresses/{liquidationAddressId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));
        urlPath = urlPath.replace(`{${"liquidationAddressId"}}`, encodeURIComponent(String(requestParameters['liquidationAddressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LiquidationAddressResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific liquidation address by its ID for a given customer.
     * Get a specific liquidation address
     */
    async liquidationAddressControllerGetLiquidationAddress(requestParameters: LiquidationAddressControllerGetLiquidationAddressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LiquidationAddressResponseDto> {
        const response = await this.liquidationAddressControllerGetLiquidationAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all liquidation addresses associated with a specific customer.
     * Get all liquidation addresses for a customer
     */
    async liquidationAddressControllerGetLiquidationAddressesRaw(requestParameters: LiquidationAddressControllerGetLiquidationAddressesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LiquidationAddressResponseDto>>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling liquidationAddressControllerGetLiquidationAddresses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v0/customers/{customerId}/liquidation_addresses`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LiquidationAddressResponseDtoFromJSON));
    }

    /**
     * Retrieve all liquidation addresses associated with a specific customer.
     * Get all liquidation addresses for a customer
     */
    async liquidationAddressControllerGetLiquidationAddresses(requestParameters: LiquidationAddressControllerGetLiquidationAddressesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LiquidationAddressResponseDto>> {
        const response = await this.liquidationAddressControllerGetLiquidationAddressesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
