/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePaymentLinkDto,
} from '../models/index';
import {
    CreatePaymentLinkDtoFromJSON,
    CreatePaymentLinkDtoToJSON,
} from '../models/index';

export interface PaymentLinksControllerCreateRequest {
    createPaymentLinkDto: CreatePaymentLinkDto;
}

export interface PaymentLinksControllerFindAllRequest {
    skip?: string;
    take?: string;
}

export interface PaymentLinksControllerFindOneRequest {
    id: string;
}

export interface PaymentLinksControllerUpdateRequest {
    id: string;
    body: object;
}

/**
 * 
 */
export class PaymentLinksApi extends runtime.BaseAPI {

    /**
     * Creates a new payment link with the provided details. Supports both simple one-time payments and complex product bundles.
     * Create a new payment link
     */
    async paymentLinksControllerCreateRaw(requestParameters: PaymentLinksControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createPaymentLinkDto'] == null) {
            throw new runtime.RequiredError(
                'createPaymentLinkDto',
                'Required parameter "createPaymentLinkDto" was null or undefined when calling paymentLinksControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/payment-links`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePaymentLinkDtoToJSON(requestParameters['createPaymentLinkDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a new payment link with the provided details. Supports both simple one-time payments and complex product bundles.
     * Create a new payment link
     */
    async paymentLinksControllerCreate(requestParameters: PaymentLinksControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentLinksControllerCreateRaw(requestParameters, initOverrides);
    }

    /**
     * Get all payment links
     */
    async paymentLinksControllerFindAllRaw(requestParameters: PaymentLinksControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/payment-links`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all payment links
     */
    async paymentLinksControllerFindAll(requestParameters: PaymentLinksControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentLinksControllerFindAllRaw(requestParameters, initOverrides);
    }

    /**
     * Get a payment link by ID
     */
    async paymentLinksControllerFindOneRaw(requestParameters: PaymentLinksControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling paymentLinksControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/payment-links/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a payment link by ID
     */
    async paymentLinksControllerFindOne(requestParameters: PaymentLinksControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentLinksControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Update a payment link
     */
    async paymentLinksControllerUpdateRaw(requestParameters: PaymentLinksControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling paymentLinksControllerUpdate().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling paymentLinksControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/payment-links/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update a payment link
     */
    async paymentLinksControllerUpdate(requestParameters: PaymentLinksControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentLinksControllerUpdateRaw(requestParameters, initOverrides);
    }

}
