/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTaxDto,
  TaxControllerCreate201Response,
  TaxControllerDeleteWithoutId400Response,
  TaxControllerUpdateWithoutId400Response,
  UpdateTaxDto,
} from '../models/index';
import {
    CreateTaxDtoFromJSON,
    CreateTaxDtoToJSON,
    TaxControllerCreate201ResponseFromJSON,
    TaxControllerCreate201ResponseToJSON,
    TaxControllerDeleteWithoutId400ResponseFromJSON,
    TaxControllerDeleteWithoutId400ResponseToJSON,
    TaxControllerUpdateWithoutId400ResponseFromJSON,
    TaxControllerUpdateWithoutId400ResponseToJSON,
    UpdateTaxDtoFromJSON,
    UpdateTaxDtoToJSON,
} from '../models/index';

export interface TaxControllerCreateRequest {
    createTaxDto: CreateTaxDto;
}

export interface TaxControllerFindAllRequest {
    skip?: number;
    take?: number;
    name?: string;
    active?: boolean;
}

export interface TaxControllerFindOneRequest {
    id: string;
}

export interface TaxControllerRemoveRequest {
    id: string;
}

export interface TaxControllerUpdateRequest {
    id: string;
    updateTaxDto: UpdateTaxDto;
}

/**
 * 
 */
export class TaxesApi extends runtime.BaseAPI {

    /**
     * Creates a new tax rate that can be applied to products, invoices, and payment links.  ## Use Cases - Set up sales tax for different regions - Create VAT rates for international customers - Configure state and local tax rates - Manage tax compliance requirements  ## Example: Create Basic Sales Tax ```json {   \"name\": \"Sales Tax\",   \"description\": \"Standard sales tax for retail transactions\",   \"percentage\": 8.5,   \"active\": true } ```  ## Required Fields - `name`: Tax name for identification (1-100 characters) - `percentage`: Tax rate percentage (0-100)  ## Optional Fields - `description`: Explanation of what this tax covers (max 255 characters) - `active`: Whether this tax is currently active (default: true) - `appIds`: Array of app IDs where this tax should be available
     * Create a new tax
     */
    async taxControllerCreateRaw(requestParameters: TaxControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaxControllerCreate201Response>> {
        if (requestParameters['createTaxDto'] == null) {
            throw new runtime.RequiredError(
                'createTaxDto',
                'Required parameter "createTaxDto" was null or undefined when calling taxControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/taxes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTaxDtoToJSON(requestParameters['createTaxDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaxControllerCreate201ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new tax rate that can be applied to products, invoices, and payment links.  ## Use Cases - Set up sales tax for different regions - Create VAT rates for international customers - Configure state and local tax rates - Manage tax compliance requirements  ## Example: Create Basic Sales Tax ```json {   \"name\": \"Sales Tax\",   \"description\": \"Standard sales tax for retail transactions\",   \"percentage\": 8.5,   \"active\": true } ```  ## Required Fields - `name`: Tax name for identification (1-100 characters) - `percentage`: Tax rate percentage (0-100)  ## Optional Fields - `description`: Explanation of what this tax covers (max 255 characters) - `active`: Whether this tax is currently active (default: true) - `appIds`: Array of app IDs where this tax should be available
     * Create a new tax
     */
    async taxControllerCreate(requestParameters: TaxControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaxControllerCreate201Response> {
        const response = await this.taxControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint requires a tax ID in the URL path. Use DELETE /api/v0/taxes/{id} instead.
     * Tax ID required for deletion
     */
    async taxControllerDeleteWithoutIdRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/taxes`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint requires a tax ID in the URL path. Use DELETE /api/v0/taxes/{id} instead.
     * Tax ID required for deletion
     */
    async taxControllerDeleteWithoutId(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taxControllerDeleteWithoutIdRaw(initOverrides);
    }

    /**
     * Retrieves a list of taxes with optional filtering and pagination.  ## Use Cases - List all available tax rates - Search taxes by name - Filter active/inactive taxes - Export tax configuration  ## Query Parameters - `skip`: Number of records to skip (default: 0, min: 0) - `take`: Number of records to return (default: 10, min: 1, max: 100) - `name`: Filter taxes by name (partial match, case-insensitive) - `active`: Filter by active status (true/false)  ## Example Request `GET /api/v0/taxes?skip=0&take=20&active=true&name=Sales`  ## Example Response ```json [   {     \"id\": \"tax_123456\",     \"name\": \"Sales Tax\",     \"description\": \"Standard sales tax for retail transactions\",     \"percentage\": 8.5,     \"active\": true,     \"created_at\": \"2024-03-20T10:00:00Z\",     \"updated_at\": \"2024-03-20T10:00:00Z\"   } ] ```
     * Get all taxes with filters
     */
    async taxControllerFindAllRaw(requestParameters: TaxControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/taxes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves a list of taxes with optional filtering and pagination.  ## Use Cases - List all available tax rates - Search taxes by name - Filter active/inactive taxes - Export tax configuration  ## Query Parameters - `skip`: Number of records to skip (default: 0, min: 0) - `take`: Number of records to return (default: 10, min: 1, max: 100) - `name`: Filter taxes by name (partial match, case-insensitive) - `active`: Filter by active status (true/false)  ## Example Request `GET /api/v0/taxes?skip=0&take=20&active=true&name=Sales`  ## Example Response ```json [   {     \"id\": \"tax_123456\",     \"name\": \"Sales Tax\",     \"description\": \"Standard sales tax for retail transactions\",     \"percentage\": 8.5,     \"active\": true,     \"created_at\": \"2024-03-20T10:00:00Z\",     \"updated_at\": \"2024-03-20T10:00:00Z\"   } ] ```
     * Get all taxes with filters
     */
    async taxControllerFindAll(requestParameters: TaxControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taxControllerFindAllRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves detailed information about a specific tax.  ## Use Cases - View tax details - Verify tax configuration - Check tax status before applying to products  ## Path Parameters - `id`: Tax UUID (required) - Must be a valid UUID format  ## Example Request `GET /api/v0/taxes/123e4567-e89b-12d3-a456-426614174000`  ## Example Response ```json {   \"id\": \"tax_123456\",   \"name\": \"Sales Tax\",   \"description\": \"Standard sales tax for retail transactions\",   \"percentage\": 8.5,   \"active\": true,   \"created_at\": \"2024-03-20T10:00:00Z\",   \"updated_at\": \"2024-03-20T10:00:00Z\" } ```
     * Get a tax by ID
     */
    async taxControllerFindOneRaw(requestParameters: TaxControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taxControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/taxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves detailed information about a specific tax.  ## Use Cases - View tax details - Verify tax configuration - Check tax status before applying to products  ## Path Parameters - `id`: Tax UUID (required) - Must be a valid UUID format  ## Example Request `GET /api/v0/taxes/123e4567-e89b-12d3-a456-426614174000`  ## Example Response ```json {   \"id\": \"tax_123456\",   \"name\": \"Sales Tax\",   \"description\": \"Standard sales tax for retail transactions\",   \"percentage\": 8.5,   \"active\": true,   \"created_at\": \"2024-03-20T10:00:00Z\",   \"updated_at\": \"2024-03-20T10:00:00Z\" } ```
     * Get a tax by ID
     */
    async taxControllerFindOne(requestParameters: TaxControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taxControllerFindOneRaw(requestParameters, initOverrides);
    }

    /**
     * Deletes an existing tax.  ## Use Cases - Remove obsolete tax rates - Clean up unused taxes - Comply with regulatory changes  ## Path Parameters - `id`: Tax UUID (required) - Must be a valid UUID format  ## Example Request `DELETE /api/v0/taxes/123e4567-e89b-12d3-a456-426614174000`  ## Warning This action cannot be undone. Consider deactivating the tax instead of deleting it if it has been used in transactions.
     * Delete a tax
     */
    async taxControllerRemoveRaw(requestParameters: TaxControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taxControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/taxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes an existing tax.  ## Use Cases - Remove obsolete tax rates - Clean up unused taxes - Comply with regulatory changes  ## Path Parameters - `id`: Tax UUID (required) - Must be a valid UUID format  ## Example Request `DELETE /api/v0/taxes/123e4567-e89b-12d3-a456-426614174000`  ## Warning This action cannot be undone. Consider deactivating the tax instead of deleting it if it has been used in transactions.
     * Delete a tax
     */
    async taxControllerRemove(requestParameters: TaxControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taxControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Updates an existing tax\'s information.  ## Use Cases - Modify tax percentage rates - Update tax descriptions - Activate/deactivate taxes - Change tax names  ## Path Parameters - `id`: Tax UUID (required) - Must be a valid UUID format  ## Example Request `PUT /api/v0/taxes/123e4567-e89b-12d3-a456-426614174000`  ## Example Request Body ```json {   \"name\": \"Updated Sales Tax\",   \"description\": \"Updated sales tax rate\",   \"percentage\": 9.0,   \"active\": true } ```  ## Notes - Only include fields that need to be updated - All fields are optional in updates - Percentage changes affect future calculations only
     * Update a tax
     */
    async taxControllerUpdateRaw(requestParameters: TaxControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling taxControllerUpdate().'
            );
        }

        if (requestParameters['updateTaxDto'] == null) {
            throw new runtime.RequiredError(
                'updateTaxDto',
                'Required parameter "updateTaxDto" was null or undefined when calling taxControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/taxes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTaxDtoToJSON(requestParameters['updateTaxDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates an existing tax\'s information.  ## Use Cases - Modify tax percentage rates - Update tax descriptions - Activate/deactivate taxes - Change tax names  ## Path Parameters - `id`: Tax UUID (required) - Must be a valid UUID format  ## Example Request `PUT /api/v0/taxes/123e4567-e89b-12d3-a456-426614174000`  ## Example Request Body ```json {   \"name\": \"Updated Sales Tax\",   \"description\": \"Updated sales tax rate\",   \"percentage\": 9.0,   \"active\": true } ```  ## Notes - Only include fields that need to be updated - All fields are optional in updates - Percentage changes affect future calculations only
     * Update a tax
     */
    async taxControllerUpdate(requestParameters: TaxControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taxControllerUpdateRaw(requestParameters, initOverrides);
    }

    /**
     * This endpoint requires a tax ID in the URL path. Use PUT /api/v0/taxes/{id} instead.
     * Tax ID required for updates
     */
    async taxControllerUpdateWithoutIdRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/taxes`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint requires a tax ID in the URL path. Use PUT /api/v0/taxes/{id} instead.
     * Tax ID required for updates
     */
    async taxControllerUpdateWithoutId(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.taxControllerUpdateWithoutIdRaw(initOverrides);
    }

}
