/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PaymentRequestDto,
  PaymentResponseDto,
  RefundResponseDto,
} from '../models/index';
import {
    PaymentRequestDtoFromJSON,
    PaymentRequestDtoToJSON,
    PaymentResponseDtoFromJSON,
    PaymentResponseDtoToJSON,
    RefundResponseDtoFromJSON,
    RefundResponseDtoToJSON,
} from '../models/index';

export interface TestPaymentControllerCreatePaymentV0Request {
    idempotencyKey: string;
    paymentRequestDto: PaymentRequestDto;
}

export interface TestPaymentControllerGetPaymentV0Request {
    id: string;
}

export interface TestPaymentControllerRefundPaymentV0Request {
    id: string;
    idempotencyKey: string;
}

/**
 * 
 */
export class TestPaymentsApi extends runtime.BaseAPI {

    /**
     * Creates a new payment. Requires an idempotency key to prevent duplicate payments on retry.      ## Idempotency Key Best Practices  1. **Generate unique keys**: Use UUIDs or similar unique identifiers, prefixed with a descriptive operation name 2. **Store keys client-side**: Save the key with the original request so you can retry with the same key 3. **Key format**: Between 6-64 alphanumeric characters 4. **Expiration**: Keys expire after 24 hours by default 5. **Use case**: Perfect for ensuring payment operations are never processed twice, even during network failures  ## Example Request (curl)  ```bash curl -X POST \\   https://api.example.com/rest-api/v0/test-payment \\   -H \'Content-Type: application/json\' \\   -H \'Client-Key: your-api-key\' \\   -H \'Client-Secret: your-api-secret\' \\   -H \'Idempotency-Key: payment_123456_unique_key\' \\   -d \'{     \"amount\": 100.00,     \"currency\": \"USD\",     \"description\": \"Test payment for order #12345\",     \"customerId\": \"cus_12345\"   }\' ```  ## Example Response (First Request)  ```json {   \"id\": \"pay_abc123xyz456\",   \"amount\": 100.00,   \"currency\": \"USD\",   \"status\": \"succeeded\",   \"timestamp\": \"2023-07-01T12:00:00.000Z\" } ```  ## Example Response (Duplicate Request)  The exact same response will be returned for any duplicate request with the same idempotency key, without creating a new payment.  ## Retry Scenario Example  Network failure during payment submission: 1. Client creates payment request with idempotency key: \"payment_123456_unique_key\" 2. Request begins processing, but network connection fails before response received 3. Client retries the exact same request with the same idempotency key 4. Server detects duplicate idempotency key and returns the result of the first request 5. No duplicate payment is created  If you retry with same key but different parameters (e.g., different amount), you\'ll receive a 409 Conflict error.
     * Process a test payment
     */
    async testPaymentControllerCreatePaymentV0Raw(requestParameters: TestPaymentControllerCreatePaymentV0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponseDto>> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling testPaymentControllerCreatePaymentV0().'
            );
        }

        if (requestParameters['paymentRequestDto'] == null) {
            throw new runtime.RequiredError(
                'paymentRequestDto',
                'Required parameter "paymentRequestDto" was null or undefined when calling testPaymentControllerCreatePaymentV0().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/test-payment`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentRequestDtoToJSON(requestParameters['paymentRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a new payment. Requires an idempotency key to prevent duplicate payments on retry.      ## Idempotency Key Best Practices  1. **Generate unique keys**: Use UUIDs or similar unique identifiers, prefixed with a descriptive operation name 2. **Store keys client-side**: Save the key with the original request so you can retry with the same key 3. **Key format**: Between 6-64 alphanumeric characters 4. **Expiration**: Keys expire after 24 hours by default 5. **Use case**: Perfect for ensuring payment operations are never processed twice, even during network failures  ## Example Request (curl)  ```bash curl -X POST \\   https://api.example.com/rest-api/v0/test-payment \\   -H \'Content-Type: application/json\' \\   -H \'Client-Key: your-api-key\' \\   -H \'Client-Secret: your-api-secret\' \\   -H \'Idempotency-Key: payment_123456_unique_key\' \\   -d \'{     \"amount\": 100.00,     \"currency\": \"USD\",     \"description\": \"Test payment for order #12345\",     \"customerId\": \"cus_12345\"   }\' ```  ## Example Response (First Request)  ```json {   \"id\": \"pay_abc123xyz456\",   \"amount\": 100.00,   \"currency\": \"USD\",   \"status\": \"succeeded\",   \"timestamp\": \"2023-07-01T12:00:00.000Z\" } ```  ## Example Response (Duplicate Request)  The exact same response will be returned for any duplicate request with the same idempotency key, without creating a new payment.  ## Retry Scenario Example  Network failure during payment submission: 1. Client creates payment request with idempotency key: \"payment_123456_unique_key\" 2. Request begins processing, but network connection fails before response received 3. Client retries the exact same request with the same idempotency key 4. Server detects duplicate idempotency key and returns the result of the first request 5. No duplicate payment is created  If you retry with same key but different parameters (e.g., different amount), you\'ll receive a 409 Conflict error.
     * Process a test payment
     */
    async testPaymentControllerCreatePaymentV0(requestParameters: TestPaymentControllerCreatePaymentV0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponseDto> {
        const response = await this.testPaymentControllerCreatePaymentV0Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get payment details by ID
     */
    async testPaymentControllerGetPaymentV0Raw(requestParameters: TestPaymentControllerGetPaymentV0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling testPaymentControllerGetPaymentV0().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/test-payment/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get payment details by ID
     */
    async testPaymentControllerGetPaymentV0(requestParameters: TestPaymentControllerGetPaymentV0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponseDto> {
        const response = await this.testPaymentControllerGetPaymentV0Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refunds an existing payment. Requires an idempotency key to prevent duplicate refunds on retry.      ## Idempotency Key Benefits for Refunds  Refunds are critical financial operations where duplicates can cause serious issues. Using idempotency keys ensures:  1. **Prevent duplicate refunds**: Even if a request times out or fails, retrying with the same key won\'t issue multiple refunds 2. **Safe retries**: Network failures or timeouts won\'t risk creating multiple refunds 3. **Consistent response**: Always get the same response for the same operation  ## Example Request (curl)  ```bash curl -X POST \\   https://api.example.com/rest-api/v0/test-payment/pay_abc123xyz456/refund \\   -H \'Content-Type: application/json\' \\   -H \'Client-Key: your-api-key\' \\   -H \'Client-Secret: your-api-secret\' \\   -H \'Idempotency-Key: refund_123456_unique_key\' ```  ## Example Response (First Request)  ```json {   \"id\": \"ref_xyz789\",   \"paymentId\": \"pay_abc123xyz456\",   \"amount\": 100.00,   \"status\": \"succeeded\",   \"timestamp\": \"2023-07-01T14:30:00.000Z\" } ```  ## Example Response (Duplicate Request)  The exact same response will be returned for any duplicate request with the same idempotency key, without creating a new refund.  ## Idempotency Key Guidelines  - Use a unique key for each distinct refund operation - Store keys client-side to ensure you can retry with the same key if needed - Keys expire after 24 hours by default
     * Refund a payment
     */
    async testPaymentControllerRefundPaymentV0Raw(requestParameters: TestPaymentControllerRefundPaymentV0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RefundResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling testPaymentControllerRefundPaymentV0().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling testPaymentControllerRefundPaymentV0().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['idempotency-key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/test-payment/{id}/refund`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RefundResponseDtoFromJSON(jsonValue));
    }

    /**
     * Refunds an existing payment. Requires an idempotency key to prevent duplicate refunds on retry.      ## Idempotency Key Benefits for Refunds  Refunds are critical financial operations where duplicates can cause serious issues. Using idempotency keys ensures:  1. **Prevent duplicate refunds**: Even if a request times out or fails, retrying with the same key won\'t issue multiple refunds 2. **Safe retries**: Network failures or timeouts won\'t risk creating multiple refunds 3. **Consistent response**: Always get the same response for the same operation  ## Example Request (curl)  ```bash curl -X POST \\   https://api.example.com/rest-api/v0/test-payment/pay_abc123xyz456/refund \\   -H \'Content-Type: application/json\' \\   -H \'Client-Key: your-api-key\' \\   -H \'Client-Secret: your-api-secret\' \\   -H \'Idempotency-Key: refund_123456_unique_key\' ```  ## Example Response (First Request)  ```json {   \"id\": \"ref_xyz789\",   \"paymentId\": \"pay_abc123xyz456\",   \"amount\": 100.00,   \"status\": \"succeeded\",   \"timestamp\": \"2023-07-01T14:30:00.000Z\" } ```  ## Example Response (Duplicate Request)  The exact same response will be returned for any duplicate request with the same idempotency key, without creating a new refund.  ## Idempotency Key Guidelines  - Use a unique key for each distinct refund operation - Store keys client-side to ensure you can retry with the same key if needed - Keys expire after 24 hours by default
     * Refund a payment
     */
    async testPaymentControllerRefundPaymentV0(requestParameters: TestPaymentControllerRefundPaymentV0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RefundResponseDto> {
        const response = await this.testPaymentControllerRefundPaymentV0Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
