/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateDirectBankTransferDto,
  CreateDirectWalletTransferDto,
  CreateExternalBankTransferDto,
  CreateExternalStablecoinTransferDto,
  CreateStablecoinConversionDto,
} from '../models/index';
import {
    CreateDirectBankTransferDtoFromJSON,
    CreateDirectBankTransferDtoToJSON,
    CreateDirectWalletTransferDtoFromJSON,
    CreateDirectWalletTransferDtoToJSON,
    CreateExternalBankTransferDtoFromJSON,
    CreateExternalBankTransferDtoToJSON,
    CreateExternalStablecoinTransferDtoFromJSON,
    CreateExternalStablecoinTransferDtoToJSON,
    CreateStablecoinConversionDtoFromJSON,
    CreateStablecoinConversionDtoToJSON,
} from '../models/index';

export interface TransferControllerCreateDirectBankTransferRequest {
    createDirectBankTransferDto: CreateDirectBankTransferDto;
}

export interface TransferControllerCreateDirectWalletTransferRequest {
    createDirectWalletTransferDto: CreateDirectWalletTransferDto;
}

export interface TransferControllerCreateExternalBankTransferRequest {
    createExternalBankTransferDto: CreateExternalBankTransferDto;
}

export interface TransferControllerCreateExternalStablecoinTransferRequest {
    createExternalStablecoinTransferDto: CreateExternalStablecoinTransferDto;
}

export interface TransferControllerCreateStablecoinConversionRequest {
    createStablecoinConversionDto: CreateStablecoinConversionDto;
}

/**
 * 
 */
export class TransfersApi extends runtime.BaseAPI {

    /**
     * Create a direct bank transfer
     */
    async transferControllerCreateDirectBankTransferRaw(requestParameters: TransferControllerCreateDirectBankTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createDirectBankTransferDto'] == null) {
            throw new runtime.RequiredError(
                'createDirectBankTransferDto',
                'Required parameter "createDirectBankTransferDto" was null or undefined when calling transferControllerCreateDirectBankTransfer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/transfers/direct-bank`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDirectBankTransferDtoToJSON(requestParameters['createDirectBankTransferDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a direct bank transfer
     */
    async transferControllerCreateDirectBankTransfer(requestParameters: TransferControllerCreateDirectBankTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferControllerCreateDirectBankTransferRaw(requestParameters, initOverrides);
    }

    /**
     * Create a direct wallet transfer
     */
    async transferControllerCreateDirectWalletTransferRaw(requestParameters: TransferControllerCreateDirectWalletTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createDirectWalletTransferDto'] == null) {
            throw new runtime.RequiredError(
                'createDirectWalletTransferDto',
                'Required parameter "createDirectWalletTransferDto" was null or undefined when calling transferControllerCreateDirectWalletTransfer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/transfers/direct-wallet`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateDirectWalletTransferDtoToJSON(requestParameters['createDirectWalletTransferDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a direct wallet transfer
     */
    async transferControllerCreateDirectWalletTransfer(requestParameters: TransferControllerCreateDirectWalletTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferControllerCreateDirectWalletTransferRaw(requestParameters, initOverrides);
    }

    /**
     * Create an external bank transfer
     */
    async transferControllerCreateExternalBankTransferRaw(requestParameters: TransferControllerCreateExternalBankTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createExternalBankTransferDto'] == null) {
            throw new runtime.RequiredError(
                'createExternalBankTransferDto',
                'Required parameter "createExternalBankTransferDto" was null or undefined when calling transferControllerCreateExternalBankTransfer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/transfers/external-bank-transfer`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateExternalBankTransferDtoToJSON(requestParameters['createExternalBankTransferDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create an external bank transfer
     */
    async transferControllerCreateExternalBankTransfer(requestParameters: TransferControllerCreateExternalBankTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferControllerCreateExternalBankTransferRaw(requestParameters, initOverrides);
    }

    /**
     * Create an external stablecoin transfer
     */
    async transferControllerCreateExternalStablecoinTransferRaw(requestParameters: TransferControllerCreateExternalStablecoinTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createExternalStablecoinTransferDto'] == null) {
            throw new runtime.RequiredError(
                'createExternalStablecoinTransferDto',
                'Required parameter "createExternalStablecoinTransferDto" was null or undefined when calling transferControllerCreateExternalStablecoinTransfer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/transfers/external-stablecoin-transfer`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateExternalStablecoinTransferDtoToJSON(requestParameters['createExternalStablecoinTransferDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create an external stablecoin transfer
     */
    async transferControllerCreateExternalStablecoinTransfer(requestParameters: TransferControllerCreateExternalStablecoinTransferRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferControllerCreateExternalStablecoinTransferRaw(requestParameters, initOverrides);
    }

    /**
     * Create a stablecoin conversion
     */
    async transferControllerCreateStablecoinConversionRaw(requestParameters: TransferControllerCreateStablecoinConversionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['createStablecoinConversionDto'] == null) {
            throw new runtime.RequiredError(
                'createStablecoinConversionDto',
                'Required parameter "createStablecoinConversionDto" was null or undefined when calling transferControllerCreateStablecoinConversion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/transfers/stablecoin-conversion`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStablecoinConversionDtoToJSON(requestParameters['createStablecoinConversionDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a stablecoin conversion
     */
    async transferControllerCreateStablecoinConversion(requestParameters: TransferControllerCreateStablecoinConversionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.transferControllerCreateStablecoinConversionRaw(requestParameters, initOverrides);
    }

}
