/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWebhookDto,
  UpdateWebhookDto,
  WebhookResponseDto,
} from '../models/index';
import {
    CreateWebhookDtoFromJSON,
    CreateWebhookDtoToJSON,
    UpdateWebhookDtoFromJSON,
    UpdateWebhookDtoToJSON,
    WebhookResponseDtoFromJSON,
    WebhookResponseDtoToJSON,
} from '../models/index';

export interface WebhookControllerCreateRequest {
    createWebhookDto: CreateWebhookDto;
}

export interface WebhookControllerFindAllRequest {
    skip?: number;
    take?: number;
}

export interface WebhookControllerFindOneRequest {
    id: string;
}

export interface WebhookControllerRemoveRequest {
    id: string;
}

export interface WebhookControllerUpdateRequest {
    id: string;
    updateWebhookDto: UpdateWebhookDto;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Creates a new webhook endpoint for receiving event notifications. Requires webhook:create scope.
     * Create a new webhook
     */
    async webhookControllerCreateRaw(requestParameters: WebhookControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookResponseDto>> {
        if (requestParameters['createWebhookDto'] == null) {
            throw new runtime.RequiredError(
                'createWebhookDto',
                'Required parameter "createWebhookDto" was null or undefined when calling webhookControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookDtoToJSON(requestParameters['createWebhookDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookResponseDtoFromJSON(jsonValue));
    }

    /**
     * Creates a new webhook endpoint for receiving event notifications. Requires webhook:create scope.
     * Create a new webhook
     */
    async webhookControllerCreate(requestParameters: WebhookControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookResponseDto> {
        const response = await this.webhookControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a list of all webhooks for your application. Requires webhook:read scope.
     * Get all webhooks
     */
    async webhookControllerFindAllRaw(requestParameters: WebhookControllerFindAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WebhookResponseDto>>> {
        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/webhooks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebhookResponseDtoFromJSON));
    }

    /**
     * Retrieves a list of all webhooks for your application. Requires webhook:read scope.
     * Get all webhooks
     */
    async webhookControllerFindAll(requestParameters: WebhookControllerFindAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WebhookResponseDto>> {
        const response = await this.webhookControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves details for a specific webhook. Requires webhook:read scope.
     * Get a webhook by id
     */
    async webhookControllerFindOneRaw(requestParameters: WebhookControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhookControllerFindOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookResponseDtoFromJSON(jsonValue));
    }

    /**
     * Retrieves details for a specific webhook. Requires webhook:read scope.
     * Get a webhook by id
     */
    async webhookControllerFindOne(requestParameters: WebhookControllerFindOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookResponseDto> {
        const response = await this.webhookControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a webhook configuration. Requires webhook:delete scope.
     * Delete a webhook
     */
    async webhookControllerRemoveRaw(requestParameters: WebhookControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhookControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookResponseDtoFromJSON(jsonValue));
    }

    /**
     * Deletes a webhook configuration. Requires webhook:delete scope.
     * Delete a webhook
     */
    async webhookControllerRemove(requestParameters: WebhookControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookResponseDto> {
        const response = await this.webhookControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing webhook configuration. Requires webhook:update scope.
     * Update a webhook
     */
    async webhookControllerUpdateRaw(requestParameters: WebhookControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling webhookControllerUpdate().'
            );
        }

        if (requestParameters['updateWebhookDto'] == null) {
            throw new runtime.RequiredError(
                'updateWebhookDto',
                'Required parameter "updateWebhookDto" was null or undefined when calling webhookControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-secret"] = await this.configuration.apiKey("x-client-secret"); // x-client-secret authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-client-key"] = await this.configuration.apiKey("x-client-key"); // x-client-key authentication
        }


        let urlPath = `/api/v0/webhooks/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWebhookDtoToJSON(requestParameters['updateWebhookDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookResponseDtoFromJSON(jsonValue));
    }

    /**
     * Updates an existing webhook configuration. Requires webhook:update scope.
     * Update a webhook
     */
    async webhookControllerUpdate(requestParameters: WebhookControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookResponseDto> {
        const response = await this.webhookControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
