/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AggregatedBalanceResponse
 */
export interface AggregatedBalanceResponse {
    /**
     * The stablecoin currency
     * @type {string}
     * @memberof AggregatedBalanceResponse
     */
    currency: AggregatedBalanceResponseCurrencyEnum;
    /**
     * The total aggregated balance across all wallets and chains
     * @type {string}
     * @memberof AggregatedBalanceResponse
     */
    totalBalance: string;
    /**
     * Detailed breakdown of balances by wallet and chain
     * @type {Array<object>}
     * @memberof AggregatedBalanceResponse
     */
    balances: Array<object>;
}


/**
 * @export
 */
export const AggregatedBalanceResponseCurrencyEnum = {
    Usdc: 'usdc',
    Eurc: 'eurc'
} as const;
export type AggregatedBalanceResponseCurrencyEnum = typeof AggregatedBalanceResponseCurrencyEnum[keyof typeof AggregatedBalanceResponseCurrencyEnum];


/**
 * Check if a given object implements the AggregatedBalanceResponse interface.
 */
export function instanceOfAggregatedBalanceResponse(value: object): value is AggregatedBalanceResponse {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('totalBalance' in value) || value['totalBalance'] === undefined) return false;
    if (!('balances' in value) || value['balances'] === undefined) return false;
    return true;
}

export function AggregatedBalanceResponseFromJSON(json: any): AggregatedBalanceResponse {
    return AggregatedBalanceResponseFromJSONTyped(json, false);
}

export function AggregatedBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregatedBalanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'totalBalance': json['total_balance'],
        'balances': json['balances'],
    };
}

export function AggregatedBalanceResponseToJSON(json: any): AggregatedBalanceResponse {
    return AggregatedBalanceResponseToJSONTyped(json, false);
}

export function AggregatedBalanceResponseToJSONTyped(value?: AggregatedBalanceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'total_balance': value['totalBalance'],
        'balances': value['balances'],
    };
}

