/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AggregatedBalanceResponse } from './AggregatedBalanceResponse';
import {
    AggregatedBalanceResponseFromJSON,
    AggregatedBalanceResponseFromJSONTyped,
    AggregatedBalanceResponseToJSON,
    AggregatedBalanceResponseToJSONTyped,
} from './AggregatedBalanceResponse';

/**
 * 
 * @export
 * @interface AllBalancesResponse
 */
export interface AllBalancesResponse {
    /**
     * USDC balance aggregation
     * @type {AggregatedBalanceResponse}
     * @memberof AllBalancesResponse
     */
    usdc: AggregatedBalanceResponse;
    /**
     * EURC balance aggregation
     * @type {AggregatedBalanceResponse}
     * @memberof AllBalancesResponse
     */
    eurc: AggregatedBalanceResponse;
    /**
     * Total value in USD equivalent
     * @type {string}
     * @memberof AllBalancesResponse
     */
    totalUsdValue: string;
}

/**
 * Check if a given object implements the AllBalancesResponse interface.
 */
export function instanceOfAllBalancesResponse(value: object): value is AllBalancesResponse {
    if (!('usdc' in value) || value['usdc'] === undefined) return false;
    if (!('eurc' in value) || value['eurc'] === undefined) return false;
    if (!('totalUsdValue' in value) || value['totalUsdValue'] === undefined) return false;
    return true;
}

export function AllBalancesResponseFromJSON(json: any): AllBalancesResponse {
    return AllBalancesResponseFromJSONTyped(json, false);
}

export function AllBalancesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllBalancesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'usdc': AggregatedBalanceResponseFromJSON(json['usdc']),
        'eurc': AggregatedBalanceResponseFromJSON(json['eurc']),
        'totalUsdValue': json['total_usd_value'],
    };
}

export function AllBalancesResponseToJSON(json: any): AllBalancesResponse {
    return AllBalancesResponseToJSONTyped(json, false);
}

export function AllBalancesResponseToJSONTyped(value?: AllBalancesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usdc': AggregatedBalanceResponseToJSON(value['usdc']),
        'eurc': AggregatedBalanceResponseToJSON(value['eurc']),
        'total_usd_value': value['totalUsdValue'],
    };
}

