/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The blockchain network where the source currency resides. Determines gas fees and transaction speed.
 * @export
 */
export const BridgePaymentRail = {
    Ethereum: 'ethereum',
    Solana: 'solana',
    Polygon: 'polygon',
    AvalancheCChain: 'avalanche_c_chain',
    Base: 'base',
    Arbitrum: 'arbitrum',
    Optimism: 'optimism',
    Stellar: 'stellar',
    Tron: 'tron',
    BridgeWallet: 'bridge_wallet',
    Wire: 'wire',
    Ach: 'ach',
    AchPush: 'ach_push',
    AchSameDay: 'ach_same_day',
    Sepa: 'sepa',
    Swift: 'swift',
    Spei: 'spei'
} as const;
export type BridgePaymentRail = typeof BridgePaymentRail[keyof typeof BridgePaymentRail];


export function instanceOfBridgePaymentRail(value: any): boolean {
    for (const key in BridgePaymentRail) {
        if (Object.prototype.hasOwnProperty.call(BridgePaymentRail, key)) {
            if (BridgePaymentRail[key as keyof typeof BridgePaymentRail] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BridgePaymentRailFromJSON(json: any): BridgePaymentRail {
    return BridgePaymentRailFromJSONTyped(json, false);
}

export function BridgePaymentRailFromJSONTyped(json: any, ignoreDiscriminator: boolean): BridgePaymentRail {
    return json as BridgePaymentRail;
}

export function BridgePaymentRailToJSON(value?: BridgePaymentRail | null): any {
    return value as any;
}

export function BridgePaymentRailToJSONTyped(value: any, ignoreDiscriminator: boolean): BridgePaymentRail {
    return value as BridgePaymentRail;
}

