/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The destination payment rail (fiat payment method)
 * @export
 */
export const BridgeFiatPaymentRail = {
    Ach: 'ach',
    AchPush: 'ach_push',
    AchSameDay: 'ach_same_day',
    Wire: 'wire',
    Sepa: 'sepa',
    Swift: 'swift',
    Spei: 'spei'
} as const;
export type BridgeFiatPaymentRail = typeof BridgeFiatPaymentRail[keyof typeof BridgeFiatPaymentRail];


export function instanceOfBridgeFiatPaymentRail(value: any): boolean {
    for (const key in BridgeFiatPaymentRail) {
        if (Object.prototype.hasOwnProperty.call(BridgeFiatPaymentRail, key)) {
            if (BridgeFiatPaymentRail[key as keyof typeof BridgeFiatPaymentRail] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BridgeFiatPaymentRailFromJSON(json: any): BridgeFiatPaymentRail {
    return BridgeFiatPaymentRailFromJSONTyped(json, false);
}

export function BridgeFiatPaymentRailFromJSONTyped(json: any, ignoreDiscriminator: boolean): BridgeFiatPaymentRail {
    return json as BridgeFiatPaymentRail;
}

export function BridgeFiatPaymentRailToJSON(value?: BridgeFiatPaymentRail | null): any {
    return value as any;
}

export function BridgeFiatPaymentRailToJSONTyped(value: any, ignoreDiscriminator: boolean): BridgeFiatPaymentRail {
    return value as BridgeFiatPaymentRail;
}

