/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaxDto
 */
export interface CreateTaxDto {
    /**
     * Tax name. Used to identify and reference this tax rate.
     * @type {string}
     * @memberof CreateTaxDto
     */
    name: string;
    /**
     * Optional description explaining what this tax covers.
     * @type {string}
     * @memberof CreateTaxDto
     */
    description?: string;
    /**
     * Tax percentage rate. Must be between 0 and 100.
     * @type {number}
     * @memberof CreateTaxDto
     */
    percentage: number;
    /**
     * Whether this tax is currently active and can be applied.
     * @type {boolean}
     * @memberof CreateTaxDto
     */
    active?: boolean;
    /**
     * Array of app IDs where this tax should be available. If not provided, tax will be available for the current app.
     * @type {Array<string>}
     * @memberof CreateTaxDto
     */
    appIds?: Array<string>;
}

/**
 * Check if a given object implements the CreateTaxDto interface.
 */
export function instanceOfCreateTaxDto(value: object): value is CreateTaxDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function CreateTaxDtoFromJSON(json: any): CreateTaxDto {
    return CreateTaxDtoFromJSONTyped(json, false);
}

export function CreateTaxDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaxDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'percentage': json['percentage'],
        'active': json['active'] == null ? undefined : json['active'],
        'appIds': json['appIds'] == null ? undefined : json['appIds'],
    };
}

export function CreateTaxDtoToJSON(json: any): CreateTaxDto {
    return CreateTaxDtoToJSONTyped(json, false);
}

export function CreateTaxDtoToJSONTyped(value?: CreateTaxDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'percentage': value['percentage'],
        'active': value['active'],
        'appIds': value['appIds'],
    };
}

