/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BridgeFiatPaymentRail } from './BridgeFiatPaymentRail';
import {
    BridgeFiatPaymentRailFromJSON,
    BridgeFiatPaymentRailFromJSONTyped,
    BridgeFiatPaymentRailToJSON,
    BridgeFiatPaymentRailToJSONTyped,
} from './BridgeFiatPaymentRail';

/**
 * 
 * @export
 * @interface CreateExternalBankTransferDto
 */
export interface CreateExternalBankTransferDto {
    /**
     * The ID of the source bridge wallet
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    sourceWalletId: string;
    /**
     * The source currency
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    sourceCurrency: string;
    /**
     * The destination currency
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    destinationCurrency: string;
    /**
     * The destination payment rail (fiat payment method)
     * @type {BridgeFiatPaymentRail}
     * @memberof CreateExternalBankTransferDto
     */
    destinationPaymentRail: BridgeFiatPaymentRail;
    /**
     * The external account ID for the bank transfer
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    externalAccountId: string;
    /**
     * The amount to transfer
     * @type {number}
     * @memberof CreateExternalBankTransferDto
     */
    amount?: number;
    /**
     * Wire transfer message (1-256 characters, only for wire transfers)
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    wireMessage?: string;
    /**
     * SEPA reference message (6-140 characters, only for SEPA transfers)
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    sepaReference?: string;
    /**
     * SWIFT reference message (1-190 characters, only for SWIFT transfers)
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    swiftReference?: string;
    /**
     * SPEI reference message (1-40 characters, only for SPEI transfers)
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    speiReference?: string;
    /**
     * SWIFT charges bearer (only for SWIFT transfers)
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    swiftCharges?: string;
    /**
     * ACH reference message (1-10 characters, only for ACH transfers)
     * @type {string}
     * @memberof CreateExternalBankTransferDto
     */
    achReference?: string;
}



/**
 * Check if a given object implements the CreateExternalBankTransferDto interface.
 */
export function instanceOfCreateExternalBankTransferDto(value: object): value is CreateExternalBankTransferDto {
    if (!('sourceWalletId' in value) || value['sourceWalletId'] === undefined) return false;
    if (!('sourceCurrency' in value) || value['sourceCurrency'] === undefined) return false;
    if (!('destinationCurrency' in value) || value['destinationCurrency'] === undefined) return false;
    if (!('destinationPaymentRail' in value) || value['destinationPaymentRail'] === undefined) return false;
    if (!('externalAccountId' in value) || value['externalAccountId'] === undefined) return false;
    return true;
}

export function CreateExternalBankTransferDtoFromJSON(json: any): CreateExternalBankTransferDto {
    return CreateExternalBankTransferDtoFromJSONTyped(json, false);
}

export function CreateExternalBankTransferDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExternalBankTransferDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceWalletId': json['sourceWalletId'],
        'sourceCurrency': json['sourceCurrency'],
        'destinationCurrency': json['destinationCurrency'],
        'destinationPaymentRail': BridgeFiatPaymentRailFromJSON(json['destinationPaymentRail']),
        'externalAccountId': json['external_account_id'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'wireMessage': json['wire_message'] == null ? undefined : json['wire_message'],
        'sepaReference': json['sepa_reference'] == null ? undefined : json['sepa_reference'],
        'swiftReference': json['swift_reference'] == null ? undefined : json['swift_reference'],
        'speiReference': json['spei_reference'] == null ? undefined : json['spei_reference'],
        'swiftCharges': json['swift_charges'] == null ? undefined : json['swift_charges'],
        'achReference': json['ach_reference'] == null ? undefined : json['ach_reference'],
    };
}

export function CreateExternalBankTransferDtoToJSON(json: any): CreateExternalBankTransferDto {
    return CreateExternalBankTransferDtoToJSONTyped(json, false);
}

export function CreateExternalBankTransferDtoToJSONTyped(value?: CreateExternalBankTransferDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceWalletId': value['sourceWalletId'],
        'sourceCurrency': value['sourceCurrency'],
        'destinationCurrency': value['destinationCurrency'],
        'destinationPaymentRail': BridgeFiatPaymentRailToJSON(value['destinationPaymentRail']),
        'external_account_id': value['externalAccountId'],
        'amount': value['amount'],
        'wire_message': value['wireMessage'],
        'sepa_reference': value['sepaReference'],
        'swift_reference': value['swiftReference'],
        'spei_reference': value['speiReference'],
        'swift_charges': value['swiftCharges'],
        'ach_reference': value['achReference'],
    };
}

