/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentLinkProductDto } from './PaymentLinkProductDto';
import {
    PaymentLinkProductDtoFromJSON,
    PaymentLinkProductDtoFromJSONTyped,
    PaymentLinkProductDtoToJSON,
    PaymentLinkProductDtoToJSONTyped,
} from './PaymentLinkProductDto';

/**
 * 
 * @export
 * @interface CreatePaymentLinkDto
 */
export interface CreatePaymentLinkDto {
    /**
     * Display title for the payment link. This appears on the checkout page and in customer communications.
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    title: string;
    /**
     * Unique URL slug for the payment link. Can be a full URL or just the path segment. Must be unique within your account.
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    url: string;
    /**
     * Detailed description of what the customer is purchasing. Supports markdown formatting.
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    description?: string;
    /**
     * Cover image URL
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    coverImage?: string;
    /**
     * Type of the payment link
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    linkType: CreatePaymentLinkDtoLinkTypeEnum;
    /**
     * Amount for the payment link
     * @type {number}
     * @memberof CreatePaymentLinkDto
     */
    amount?: number;
    /**
     * Payment for ID
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    paymentForId?: string;
    /**
     * Customer ID
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    customerId?: string;
    /**
     * Array of products in the payment link
     * @type {Array<PaymentLinkProductDto>}
     * @memberof CreatePaymentLinkDto
     */
    paymentLinkProducts?: Array<PaymentLinkProductDto>;
    /**
     * Whether the payment link is for all products
     * @type {boolean}
     * @memberof CreatePaymentLinkDto
     */
    isForAllProduct?: boolean;
    /**
     * Whether to allow quantity adjustment
     * @type {boolean}
     * @memberof CreatePaymentLinkDto
     */
    allowQuantityAdjustment: boolean;
    /**
     * Whether to collect tax
     * @type {boolean}
     * @memberof CreatePaymentLinkDto
     */
    collectTax: boolean;
    /**
     * Tax ID
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    taxId?: string;
    /**
     * Whether to collect address
     * @type {boolean}
     * @memberof CreatePaymentLinkDto
     */
    collectAddress: boolean;
    /**
     * Whether to limit payments
     * @type {boolean}
     * @memberof CreatePaymentLinkDto
     */
    limitPayments?: boolean;
    /**
     * Maximum number of payments
     * @type {number}
     * @memberof CreatePaymentLinkDto
     */
    maxPayments?: number;
    /**
     * Custom fields
     * @type {object}
     * @memberof CreatePaymentLinkDto
     */
    customFields?: object;
    /**
     * Whether to allow mobile payment
     * @type {boolean}
     * @memberof CreatePaymentLinkDto
     */
    allowMobilePayment: boolean;
    /**
     * Currency
     * @type {string}
     * @memberof CreatePaymentLinkDto
     */
    currency: CreatePaymentLinkDtoCurrencyEnum;
    /**
     * Expiration date
     * @type {Date}
     * @memberof CreatePaymentLinkDto
     */
    expirationDate?: Date;
}


/**
 * @export
 */
export const CreatePaymentLinkDtoLinkTypeEnum = {
    Invoice: 'INVOICE',
    Product: 'PRODUCT',
    Collection: 'COLLECTION',
    Donation: 'DONATION'
} as const;
export type CreatePaymentLinkDtoLinkTypeEnum = typeof CreatePaymentLinkDtoLinkTypeEnum[keyof typeof CreatePaymentLinkDtoLinkTypeEnum];

/**
 * @export
 */
export const CreatePaymentLinkDtoCurrencyEnum = {
    Usdc: 'usdc',
    Eurc: 'eurc'
} as const;
export type CreatePaymentLinkDtoCurrencyEnum = typeof CreatePaymentLinkDtoCurrencyEnum[keyof typeof CreatePaymentLinkDtoCurrencyEnum];


/**
 * Check if a given object implements the CreatePaymentLinkDto interface.
 */
export function instanceOfCreatePaymentLinkDto(value: object): value is CreatePaymentLinkDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('linkType' in value) || value['linkType'] === undefined) return false;
    if (!('allowQuantityAdjustment' in value) || value['allowQuantityAdjustment'] === undefined) return false;
    if (!('collectTax' in value) || value['collectTax'] === undefined) return false;
    if (!('collectAddress' in value) || value['collectAddress'] === undefined) return false;
    if (!('allowMobilePayment' in value) || value['allowMobilePayment'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    return true;
}

export function CreatePaymentLinkDtoFromJSON(json: any): CreatePaymentLinkDto {
    return CreatePaymentLinkDtoFromJSONTyped(json, false);
}

export function CreatePaymentLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentLinkDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'url': json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverImage': json['coverImage'] == null ? undefined : json['coverImage'],
        'linkType': json['linkType'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'paymentForId': json['paymentForId'] == null ? undefined : json['paymentForId'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'paymentLinkProducts': json['paymentLinkProducts'] == null ? undefined : ((json['paymentLinkProducts'] as Array<any>).map(PaymentLinkProductDtoFromJSON)),
        'isForAllProduct': json['isForAllProduct'] == null ? undefined : json['isForAllProduct'],
        'allowQuantityAdjustment': json['allowQuantityAdjustment'],
        'collectTax': json['collectTax'],
        'taxId': json['taxId'] == null ? undefined : json['taxId'],
        'collectAddress': json['collectAddress'],
        'limitPayments': json['limitPayments'] == null ? undefined : json['limitPayments'],
        'maxPayments': json['maxPayments'] == null ? undefined : json['maxPayments'],
        'customFields': json['customFields'] == null ? undefined : json['customFields'],
        'allowMobilePayment': json['allowMobilePayment'],
        'currency': json['currency'],
        'expirationDate': json['expiration_date'] == null ? undefined : (new Date(json['expiration_date'])),
    };
}

export function CreatePaymentLinkDtoToJSON(json: any): CreatePaymentLinkDto {
    return CreatePaymentLinkDtoToJSONTyped(json, false);
}

export function CreatePaymentLinkDtoToJSONTyped(value?: CreatePaymentLinkDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'url': value['url'],
        'description': value['description'],
        'coverImage': value['coverImage'],
        'linkType': value['linkType'],
        'amount': value['amount'],
        'paymentForId': value['paymentForId'],
        'customerId': value['customerId'],
        'paymentLinkProducts': value['paymentLinkProducts'] == null ? undefined : ((value['paymentLinkProducts'] as Array<any>).map(PaymentLinkProductDtoToJSON)),
        'isForAllProduct': value['isForAllProduct'],
        'allowQuantityAdjustment': value['allowQuantityAdjustment'],
        'collectTax': value['collectTax'],
        'taxId': value['taxId'],
        'collectAddress': value['collectAddress'],
        'limitPayments': value['limitPayments'],
        'maxPayments': value['maxPayments'],
        'customFields': value['customFields'],
        'allowMobilePayment': value['allowMobilePayment'],
        'currency': value['currency'],
        'expiration_date': value['expirationDate'] == null ? value['expirationDate'] : value['expirationDate'].toISOString(),
    };
}

