/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BridgePaymentRail } from './BridgePaymentRail';
import {
    BridgePaymentRailFromJSON,
    BridgePaymentRailFromJSONTyped,
    BridgePaymentRailToJSON,
    BridgePaymentRailToJSONTyped,
} from './BridgePaymentRail';
import type { FiatCurrency } from './FiatCurrency';
import {
    FiatCurrencyFromJSON,
    FiatCurrencyFromJSONTyped,
    FiatCurrencyToJSON,
    FiatCurrencyToJSONTyped,
} from './FiatCurrency';
import type { StableCoinCurrency } from './StableCoinCurrency';
import {
    StableCoinCurrencyFromJSON,
    StableCoinCurrencyFromJSONTyped,
    StableCoinCurrencyToJSON,
    StableCoinCurrencyToJSONTyped,
} from './StableCoinCurrency';

/**
 * 
 * @export
 * @interface CreateBankPaymentIntentDto
 */
export interface CreateBankPaymentIntentDto {
    /**
     * The banking payment method to use for the transfer. Determines processing time and fees.
     * @type {BridgePaymentRail}
     * @memberof CreateBankPaymentIntentDto
     */
    sourcePaymentRail: BridgePaymentRail;
    /**
     * The fiat currency to convert FROM. Must match the currency of the source payment rail.
     * @type {FiatCurrency}
     * @memberof CreateBankPaymentIntentDto
     */
    sourceCurrency: FiatCurrency;
    /**
     * The stablecoin currency to convert TO. The customer will receive this currency.
     * @type {StableCoinCurrency}
     * @memberof CreateBankPaymentIntentDto
     */
    destinationCurrency: StableCoinCurrency;
    /**
     * The blockchain network where the stablecoin will be delivered. Must support the destination currency.
     * @type {BridgePaymentRail}
     * @memberof CreateBankPaymentIntentDto
     */
    destinationNetwork: BridgePaymentRail;
    /**
     * Destination wallet address. Supports Ethereum (0x...) and Solana address formats.
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    destinationAddress?: string;
    /**
     * Payment amount (optional for flexible amount)
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    amount?: string;
    /**
     * Customer first name
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerFirstName?: string;
    /**
     * Customer last name
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerLastName?: string;
    /**
     * Customer email address
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerEmail?: string;
    /**
     * Customer address
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerAddress?: string;
    /**
     * Customer country
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerCountry?: string;
    /**
     * Customer country ISO code
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerCountryISO?: string;
    /**
     * Customer province/state
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerProvince?: string;
    /**
     * Customer province/state ISO code
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    customerProvinceISO?: string;
    /**
     * Customer phone number
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    phoneNumber?: string;
    /**
     * Wire transfer message (for WIRE transfers)
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    wireMessage?: string;
    /**
     * SEPA reference (for SEPA transfers)
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    sepaReference?: string;
    /**
     * ACH reference (for ACH transfers)
     * @type {string}
     * @memberof CreateBankPaymentIntentDto
     */
    achReference?: string;
}



/**
 * Check if a given object implements the CreateBankPaymentIntentDto interface.
 */
export function instanceOfCreateBankPaymentIntentDto(value: object): value is CreateBankPaymentIntentDto {
    if (!('sourcePaymentRail' in value) || value['sourcePaymentRail'] === undefined) return false;
    if (!('sourceCurrency' in value) || value['sourceCurrency'] === undefined) return false;
    if (!('destinationCurrency' in value) || value['destinationCurrency'] === undefined) return false;
    if (!('destinationNetwork' in value) || value['destinationNetwork'] === undefined) return false;
    return true;
}

export function CreateBankPaymentIntentDtoFromJSON(json: any): CreateBankPaymentIntentDto {
    return CreateBankPaymentIntentDtoFromJSONTyped(json, false);
}

export function CreateBankPaymentIntentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBankPaymentIntentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sourcePaymentRail': BridgePaymentRailFromJSON(json['sourcePaymentRail']),
        'sourceCurrency': FiatCurrencyFromJSON(json['sourceCurrency']),
        'destinationCurrency': StableCoinCurrencyFromJSON(json['destinationCurrency']),
        'destinationNetwork': BridgePaymentRailFromJSON(json['destinationNetwork']),
        'destinationAddress': json['destinationAddress'] == null ? undefined : json['destinationAddress'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'customerFirstName': json['customer_first_name'] == null ? undefined : json['customer_first_name'],
        'customerLastName': json['customer_last_name'] == null ? undefined : json['customer_last_name'],
        'customerEmail': json['customer_email'] == null ? undefined : json['customer_email'],
        'customerAddress': json['customer_address'] == null ? undefined : json['customer_address'],
        'customerCountry': json['customer_country'] == null ? undefined : json['customer_country'],
        'customerCountryISO': json['customer_countryISO'] == null ? undefined : json['customer_countryISO'],
        'customerProvince': json['customer_province'] == null ? undefined : json['customer_province'],
        'customerProvinceISO': json['customer_provinceISO'] == null ? undefined : json['customer_provinceISO'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'wireMessage': json['wire_message'] == null ? undefined : json['wire_message'],
        'sepaReference': json['sepa_reference'] == null ? undefined : json['sepa_reference'],
        'achReference': json['ach_reference'] == null ? undefined : json['ach_reference'],
    };
}

export function CreateBankPaymentIntentDtoToJSON(json: any): CreateBankPaymentIntentDto {
    return CreateBankPaymentIntentDtoToJSONTyped(json, false);
}

export function CreateBankPaymentIntentDtoToJSONTyped(value?: CreateBankPaymentIntentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourcePaymentRail': BridgePaymentRailToJSON(value['sourcePaymentRail']),
        'sourceCurrency': FiatCurrencyToJSON(value['sourceCurrency']),
        'destinationCurrency': StableCoinCurrencyToJSON(value['destinationCurrency']),
        'destinationNetwork': BridgePaymentRailToJSON(value['destinationNetwork']),
        'destinationAddress': value['destinationAddress'],
        'amount': value['amount'],
        'customer_first_name': value['customerFirstName'],
        'customer_last_name': value['customerLastName'],
        'customer_email': value['customerEmail'],
        'customer_address': value['customerAddress'],
        'customer_country': value['customerCountry'],
        'customer_countryISO': value['customerCountryISO'],
        'customer_province': value['customerProvince'],
        'customer_provinceISO': value['customerProvinceISO'],
        'phoneNumber': value['phoneNumber'],
        'wire_message': value['wireMessage'],
        'sepa_reference': value['sepaReference'],
        'ach_reference': value['achReference'],
    };
}

