/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDirectWalletTransferDto
 */
export interface CreateDirectWalletTransferDto {
    /**
     * The ID of the bridge wallet to transfer from
     * @type {string}
     * @memberof CreateDirectWalletTransferDto
     */
    walletId: string;
    /**
     * The network to use for the transfer
     * @type {string}
     * @memberof CreateDirectWalletTransferDto
     */
    network: string;
    /**
     * The stablecoin currency to use
     * @type {string}
     * @memberof CreateDirectWalletTransferDto
     */
    stableCoinCurrency: string;
    /**
     * The amount to transfer
     * @type {number}
     * @memberof CreateDirectWalletTransferDto
     */
    amount: number;
}

/**
 * Check if a given object implements the CreateDirectWalletTransferDto interface.
 */
export function instanceOfCreateDirectWalletTransferDto(value: object): value is CreateDirectWalletTransferDto {
    if (!('walletId' in value) || value['walletId'] === undefined) return false;
    if (!('network' in value) || value['network'] === undefined) return false;
    if (!('stableCoinCurrency' in value) || value['stableCoinCurrency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateDirectWalletTransferDtoFromJSON(json: any): CreateDirectWalletTransferDto {
    return CreateDirectWalletTransferDtoFromJSONTyped(json, false);
}

export function CreateDirectWalletTransferDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDirectWalletTransferDto {
    if (json == null) {
        return json;
    }
    return {
        
        'walletId': json['walletId'],
        'network': json['network'],
        'stableCoinCurrency': json['stableCoinCurrency'],
        'amount': json['amount'],
    };
}

export function CreateDirectWalletTransferDtoToJSON(json: any): CreateDirectWalletTransferDto {
    return CreateDirectWalletTransferDtoToJSONTyped(json, false);
}

export function CreateDirectWalletTransferDtoToJSONTyped(value?: CreateDirectWalletTransferDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'walletId': value['walletId'],
        'network': value['network'],
        'stableCoinCurrency': value['stableCoinCurrency'],
        'amount': value['amount'],
    };
}

