/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStablecoinConversionDto
 */
export interface CreateStablecoinConversionDto {
    /**
     * The ID of the bridge wallet to use
     * @type {string}
     * @memberof CreateStablecoinConversionDto
     */
    walletId: string;
    /**
     * The source network
     * @type {string}
     * @memberof CreateStablecoinConversionDto
     */
    sourceNetwork: string;
    /**
     * The source currency
     * @type {string}
     * @memberof CreateStablecoinConversionDto
     */
    sourceCurrency: string;
    /**
     * The destination currency
     * @type {string}
     * @memberof CreateStablecoinConversionDto
     */
    destinationCurrency: string;
    /**
     * The amount to convert
     * @type {number}
     * @memberof CreateStablecoinConversionDto
     */
    amount: number;
}

/**
 * Check if a given object implements the CreateStablecoinConversionDto interface.
 */
export function instanceOfCreateStablecoinConversionDto(value: object): value is CreateStablecoinConversionDto {
    if (!('walletId' in value) || value['walletId'] === undefined) return false;
    if (!('sourceNetwork' in value) || value['sourceNetwork'] === undefined) return false;
    if (!('sourceCurrency' in value) || value['sourceCurrency'] === undefined) return false;
    if (!('destinationCurrency' in value) || value['destinationCurrency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateStablecoinConversionDtoFromJSON(json: any): CreateStablecoinConversionDto {
    return CreateStablecoinConversionDtoFromJSONTyped(json, false);
}

export function CreateStablecoinConversionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStablecoinConversionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'walletId': json['walletId'],
        'sourceNetwork': json['sourceNetwork'],
        'sourceCurrency': json['sourceCurrency'],
        'destinationCurrency': json['destinationCurrency'],
        'amount': json['amount'],
    };
}

export function CreateStablecoinConversionDtoToJSON(json: any): CreateStablecoinConversionDto {
    return CreateStablecoinConversionDtoToJSONTyped(json, false);
}

export function CreateStablecoinConversionDtoToJSONTyped(value?: CreateStablecoinConversionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'walletId': value['walletId'],
        'sourceNetwork': value['sourceNetwork'],
        'sourceCurrency': value['sourceCurrency'],
        'destinationCurrency': value['destinationCurrency'],
        'amount': value['amount'],
    };
}

