/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInvoiceDto
 */
export interface CreateInvoiceDto {
    /**
     * Name of the invoice
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    name: string;
    /**
     * Email address
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    email: string;
    /**
     * Customer ID
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    customerId: string;
    /**
     * Currency for the invoice
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    currency: CreateInvoiceDtoCurrencyEnum;
    /**
     * 
     * @type {object}
     * @memberof CreateInvoiceDto
     */
    items: object;
    /**
     * Due date of the invoice
     * @type {Date}
     * @memberof CreateInvoiceDto
     */
    dueDate: Date;
    /**
     * Delivery method
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    delivery: CreateInvoiceDtoDeliveryEnum;
    /**
     * Whether to generate a payment link
     * @type {boolean}
     * @memberof CreateInvoiceDto
     */
    paymentLink: boolean;
    /**
     * Array of accepted payment methods
     * @type {Array<string>}
     * @memberof CreateInvoiceDto
     */
    paymentMethods: Array<CreateInvoiceDtoPaymentMethodsEnum>;
    /**
     * Invoice status
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    status: CreateInvoiceDtoStatusEnum;
    /**
     * Address
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    address?: string;
    /**
     * Phone number
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    phoneNumber?: string;
    /**
     * Send date
     * @type {Date}
     * @memberof CreateInvoiceDto
     */
    sendDate?: Date;
    /**
     * Logo URL
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    logo?: string;
    /**
     * Allow partial payments
     * @type {boolean}
     * @memberof CreateInvoiceDto
     */
    partialPayment: boolean;
    /**
     * Tax ID
     * @type {string}
     * @memberof CreateInvoiceDto
     */
    taxId?: string;
}


/**
 * @export
 */
export const CreateInvoiceDtoCurrencyEnum = {
    Usdc: 'usdc',
    Eurc: 'eurc'
} as const;
export type CreateInvoiceDtoCurrencyEnum = typeof CreateInvoiceDtoCurrencyEnum[keyof typeof CreateInvoiceDtoCurrencyEnum];

/**
 * @export
 */
export const CreateInvoiceDtoDeliveryEnum = {
    Email: 'EMAIL',
    Manually: 'MANUALLY'
} as const;
export type CreateInvoiceDtoDeliveryEnum = typeof CreateInvoiceDtoDeliveryEnum[keyof typeof CreateInvoiceDtoDeliveryEnum];

/**
 * @export
 */
export const CreateInvoiceDtoPaymentMethodsEnum = {
    Ach: 'ACH',
    BankTransfer: 'BANK_TRANSFER',
    CreditCard: 'CREDIT_CARD',
    Cash: 'CASH',
    MobileMoney: 'MOBILE_MONEY',
    Crypto: 'CRYPTO'
} as const;
export type CreateInvoiceDtoPaymentMethodsEnum = typeof CreateInvoiceDtoPaymentMethodsEnum[keyof typeof CreateInvoiceDtoPaymentMethodsEnum];

/**
 * @export
 */
export const CreateInvoiceDtoStatusEnum = {
    Draft: 'DRAFT',
    Open: 'OPEN',
    Pastdue: 'PASTDUE',
    Paid: 'PAID',
    Partiallypaid: 'PARTIALLYPAID'
} as const;
export type CreateInvoiceDtoStatusEnum = typeof CreateInvoiceDtoStatusEnum[keyof typeof CreateInvoiceDtoStatusEnum];


/**
 * Check if a given object implements the CreateInvoiceDto interface.
 */
export function instanceOfCreateInvoiceDto(value: object): value is CreateInvoiceDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    if (!('delivery' in value) || value['delivery'] === undefined) return false;
    if (!('paymentLink' in value) || value['paymentLink'] === undefined) return false;
    if (!('paymentMethods' in value) || value['paymentMethods'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('partialPayment' in value) || value['partialPayment'] === undefined) return false;
    return true;
}

export function CreateInvoiceDtoFromJSON(json: any): CreateInvoiceDto {
    return CreateInvoiceDtoFromJSONTyped(json, false);
}

export function CreateInvoiceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInvoiceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'customerId': json['customer_id'],
        'currency': json['currency'],
        'items': json['items'],
        'dueDate': (new Date(json['due_date'])),
        'delivery': json['delivery'],
        'paymentLink': json['payment_link'],
        'paymentMethods': json['payment_methods'],
        'status': json['status'],
        'address': json['address'] == null ? undefined : json['address'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'sendDate': json['send_date'] == null ? undefined : (new Date(json['send_date'])),
        'logo': json['logo'] == null ? undefined : json['logo'],
        'partialPayment': json['partial_payment'],
        'taxId': json['taxId'] == null ? undefined : json['taxId'],
    };
}

export function CreateInvoiceDtoToJSON(json: any): CreateInvoiceDto {
    return CreateInvoiceDtoToJSONTyped(json, false);
}

export function CreateInvoiceDtoToJSONTyped(value?: CreateInvoiceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'customer_id': value['customerId'],
        'currency': value['currency'],
        'items': value['items'],
        'due_date': value['dueDate'].toISOString(),
        'delivery': value['delivery'],
        'payment_link': value['paymentLink'],
        'payment_methods': value['paymentMethods'],
        'status': value['status'],
        'address': value['address'],
        'phone_number': value['phoneNumber'],
        'send_date': value['sendDate'] == null ? value['sendDate'] : value['sendDate'].toISOString(),
        'logo': value['logo'],
        'partial_payment': value['partialPayment'],
        'taxId': value['taxId'],
    };
}

