/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExternalStablecoinTransferDto
 */
export interface CreateExternalStablecoinTransferDto {
    /**
     * The ID of the source bridge wallet
     * @type {string}
     * @memberof CreateExternalStablecoinTransferDto
     */
    sourceWalletId: string;
    /**
     * The source currency
     * @type {string}
     * @memberof CreateExternalStablecoinTransferDto
     */
    sourceCurrency: string;
    /**
     * The destination currency
     * @type {string}
     * @memberof CreateExternalStablecoinTransferDto
     */
    destinationCurrency: string;
    /**
     * Blockchain memo for the transfer
     * @type {string}
     * @memberof CreateExternalStablecoinTransferDto
     */
    blockchainMemo?: string;
    /**
     * Beneficiary ID for the stablecoin transfer
     * @type {string}
     * @memberof CreateExternalStablecoinTransferDto
     */
    beneficiaryId: string;
    /**
     * The amount to transfer
     * @type {number}
     * @memberof CreateExternalStablecoinTransferDto
     */
    amount?: number;
}

/**
 * Check if a given object implements the CreateExternalStablecoinTransferDto interface.
 */
export function instanceOfCreateExternalStablecoinTransferDto(value: object): value is CreateExternalStablecoinTransferDto {
    if (!('sourceWalletId' in value) || value['sourceWalletId'] === undefined) return false;
    if (!('sourceCurrency' in value) || value['sourceCurrency'] === undefined) return false;
    if (!('destinationCurrency' in value) || value['destinationCurrency'] === undefined) return false;
    if (!('beneficiaryId' in value) || value['beneficiaryId'] === undefined) return false;
    return true;
}

export function CreateExternalStablecoinTransferDtoFromJSON(json: any): CreateExternalStablecoinTransferDto {
    return CreateExternalStablecoinTransferDtoFromJSONTyped(json, false);
}

export function CreateExternalStablecoinTransferDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExternalStablecoinTransferDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceWalletId': json['sourceWalletId'],
        'sourceCurrency': json['sourceCurrency'],
        'destinationCurrency': json['destinationCurrency'],
        'blockchainMemo': json['blockchain_memo'] == null ? undefined : json['blockchain_memo'],
        'beneficiaryId': json['beneficiaryId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function CreateExternalStablecoinTransferDtoToJSON(json: any): CreateExternalStablecoinTransferDto {
    return CreateExternalStablecoinTransferDtoToJSONTyped(json, false);
}

export function CreateExternalStablecoinTransferDtoToJSONTyped(value?: CreateExternalStablecoinTransferDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceWalletId': value['sourceWalletId'],
        'sourceCurrency': value['sourceCurrency'],
        'destinationCurrency': value['destinationCurrency'],
        'blockchain_memo': value['blockchainMemo'],
        'beneficiaryId': value['beneficiaryId'],
        'amount': value['amount'],
    };
}

