/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerStatus } from './CustomerStatus';
import {
    CustomerStatusFromJSON,
    CustomerStatusFromJSONTyped,
    CustomerStatusToJSON,
    CustomerStatusToJSONTyped,
} from './CustomerStatus';
import type { CustomerType } from './CustomerType';
import {
    CustomerTypeFromJSON,
    CustomerTypeFromJSONTyped,
    CustomerTypeToJSON,
    CustomerTypeToJSONTyped,
} from './CustomerType';

/**
 * 
 * @export
 * @interface CreateCustomerDto
 */
export interface CreateCustomerDto {
    /**
     * Customer's first name. Used for personalization and legal documentation.
     * @type {string}
     * @memberof CreateCustomerDto
     */
    firstName: string;
    /**
     * Customer's last name. Used for personalization and legal documentation.
     * @type {string}
     * @memberof CreateCustomerDto
     */
    lastName: string;
    /**
     * Customer's email address. Used for notifications, receipts, and account management. Must be a valid email format.
     * @type {string}
     * @memberof CreateCustomerDto
     */
    email?: string;
    /**
     * Customer's phone number. Used for SMS notifications and verification. Include country code for international numbers.
     * @type {string}
     * @memberof CreateCustomerDto
     */
    phoneNumber: string;
    /**
     * Type of customer account. Determines available features and compliance requirements.
     * @type {CustomerType}
     * @memberof CreateCustomerDto
     */
    customerType?: CustomerType;
    /**
     * Current status of the customer account. Controls access to services and features.
     * @type {CustomerStatus}
     * @memberof CreateCustomerDto
     */
    status?: CustomerStatus;
}



/**
 * Check if a given object implements the CreateCustomerDto interface.
 */
export function instanceOfCreateCustomerDto(value: object): value is CreateCustomerDto {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    return true;
}

export function CreateCustomerDtoFromJSON(json: any): CreateCustomerDto {
    return CreateCustomerDtoFromJSONTyped(json, false);
}

export function CreateCustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'],
        'customerType': json['customer_type'] == null ? undefined : CustomerTypeFromJSON(json['customer_type']),
        'status': json['status'] == null ? undefined : CustomerStatusFromJSON(json['status']),
    };
}

export function CreateCustomerDtoToJSON(json: any): CreateCustomerDto {
    return CreateCustomerDtoToJSONTyped(json, false);
}

export function CreateCustomerDtoToJSONTyped(value?: CreateCustomerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'customer_type': CustomerTypeToJSON(value['customerType']),
        'status': CustomerStatusToJSON(value['status']),
    };
}

