/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DestinationCurrency } from './DestinationCurrency';
import {
    DestinationCurrencyFromJSON,
    DestinationCurrencyFromJSONTyped,
    DestinationCurrencyToJSON,
    DestinationCurrencyToJSONTyped,
} from './DestinationCurrency';
import type { BridgePaymentRail } from './BridgePaymentRail';
import {
    BridgePaymentRailFromJSON,
    BridgePaymentRailFromJSONTyped,
    BridgePaymentRailToJSON,
    BridgePaymentRailToJSONTyped,
} from './BridgePaymentRail';

/**
 * 
 * @export
 * @interface CreateLiquidationAddressDto
 */
export interface CreateLiquidationAddressDto {
    /**
     * The blockchain chain for the liquidation address
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    chain: CreateLiquidationAddressDtoChainEnum;
    /**
     * The currency for the liquidation address
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    currency: CreateLiquidationAddressDtoCurrencyEnum;
    /**
     * The liquidation address on the blockchain
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    address: string;
    /**
     * External bank account to send funds to
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    externalAccountId?: string;
    /**
     * Developer's prefunded account id
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    prefundedAccountId?: string;
    /**
     * Bridge Wallet to send funds to
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    bridgeWalletId?: string;
    /**
     * Payment rail for sending funds
     * @type {BridgePaymentRail}
     * @memberof CreateLiquidationAddressDto
     */
    destinationPaymentRail?: BridgePaymentRail;
    /**
     * Currency for sending funds
     * @type {DestinationCurrency}
     * @memberof CreateLiquidationAddressDto
     */
    destinationCurrency?: DestinationCurrency;
    /**
     * Message for wire transfers
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    destinationWireMessage?: string;
    /**
     * Reference for SEPA transactions
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    destinationSepaReference?: string;
    /**
     * Reference for ACH transactions
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    destinationAchReference?: string;
    /**
     * Crypto wallet address for crypto transfers
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    destinationAddress?: string;
    /**
     * Memo for blockchain transactions
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    destinationBlockchainMemo?: string;
    /**
     * Address to return funds on failed transactions (Not supported on Stellar)
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    returnAddress?: string;
    /**
     * Custom developer fee percentage (Base 100 percentage: 10.2% = "10.2")
     * @type {string}
     * @memberof CreateLiquidationAddressDto
     */
    customDeveloperFeePercent?: string;
}


/**
 * @export
 */
export const CreateLiquidationAddressDtoChainEnum = {
    Ethereum: 'ethereum',
    Solana: 'solana',
    Polygon: 'polygon',
    AvalancheCChain: 'avalanche_c_chain',
    Base: 'base',
    Arbitrum: 'arbitrum',
    Optimism: 'optimism',
    Stellar: 'stellar',
    Tron: 'tron'
} as const;
export type CreateLiquidationAddressDtoChainEnum = typeof CreateLiquidationAddressDtoChainEnum[keyof typeof CreateLiquidationAddressDtoChainEnum];

/**
 * @export
 */
export const CreateLiquidationAddressDtoCurrencyEnum = {
    Usdc: 'usdc',
    Eurc: 'eurc',
    Dai: 'dai',
    Pyusd: 'pyusd',
    Usdt: 'usdt'
} as const;
export type CreateLiquidationAddressDtoCurrencyEnum = typeof CreateLiquidationAddressDtoCurrencyEnum[keyof typeof CreateLiquidationAddressDtoCurrencyEnum];


/**
 * Check if a given object implements the CreateLiquidationAddressDto interface.
 */
export function instanceOfCreateLiquidationAddressDto(value: object): value is CreateLiquidationAddressDto {
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function CreateLiquidationAddressDtoFromJSON(json: any): CreateLiquidationAddressDto {
    return CreateLiquidationAddressDtoFromJSONTyped(json, false);
}

export function CreateLiquidationAddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLiquidationAddressDto {
    if (json == null) {
        return json;
    }
    return {
        
        'chain': json['chain'],
        'currency': json['currency'],
        'address': json['address'],
        'externalAccountId': json['external_account_id'] == null ? undefined : json['external_account_id'],
        'prefundedAccountId': json['prefunded_account_id'] == null ? undefined : json['prefunded_account_id'],
        'bridgeWalletId': json['bridge_wallet_id'] == null ? undefined : json['bridge_wallet_id'],
        'destinationPaymentRail': json['destination_payment_rail'] == null ? undefined : BridgePaymentRailFromJSON(json['destination_payment_rail']),
        'destinationCurrency': json['destination_currency'] == null ? undefined : DestinationCurrencyFromJSON(json['destination_currency']),
        'destinationWireMessage': json['destination_wire_message'] == null ? undefined : json['destination_wire_message'],
        'destinationSepaReference': json['destination_sepa_reference'] == null ? undefined : json['destination_sepa_reference'],
        'destinationAchReference': json['destination_ach_reference'] == null ? undefined : json['destination_ach_reference'],
        'destinationAddress': json['destination_address'] == null ? undefined : json['destination_address'],
        'destinationBlockchainMemo': json['destination_blockchain_memo'] == null ? undefined : json['destination_blockchain_memo'],
        'returnAddress': json['return_address'] == null ? undefined : json['return_address'],
        'customDeveloperFeePercent': json['custom_developer_fee_percent'] == null ? undefined : json['custom_developer_fee_percent'],
    };
}

export function CreateLiquidationAddressDtoToJSON(json: any): CreateLiquidationAddressDto {
    return CreateLiquidationAddressDtoToJSONTyped(json, false);
}

export function CreateLiquidationAddressDtoToJSONTyped(value?: CreateLiquidationAddressDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chain': value['chain'],
        'currency': value['currency'],
        'address': value['address'],
        'external_account_id': value['externalAccountId'],
        'prefunded_account_id': value['prefundedAccountId'],
        'bridge_wallet_id': value['bridgeWalletId'],
        'destination_payment_rail': BridgePaymentRailToJSON(value['destinationPaymentRail']),
        'destination_currency': DestinationCurrencyToJSON(value['destinationCurrency']),
        'destination_wire_message': value['destinationWireMessage'],
        'destination_sepa_reference': value['destinationSepaReference'],
        'destination_ach_reference': value['destinationAchReference'],
        'destination_address': value['destinationAddress'],
        'destination_blockchain_memo': value['destinationBlockchainMemo'],
        'return_address': value['returnAddress'],
        'custom_developer_fee_percent': value['customDeveloperFeePercent'],
    };
}

