/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BridgePaymentRail } from './BridgePaymentRail';
import {
    BridgePaymentRailFromJSON,
    BridgePaymentRailFromJSONTyped,
    BridgePaymentRailToJSON,
    BridgePaymentRailToJSONTyped,
} from './BridgePaymentRail';
import type { StableCoinCurrency } from './StableCoinCurrency';
import {
    StableCoinCurrencyFromJSON,
    StableCoinCurrencyFromJSONTyped,
    StableCoinCurrencyToJSON,
    StableCoinCurrencyToJSONTyped,
} from './StableCoinCurrency';

/**
 * 
 * @export
 * @interface CreateStablePaymentIntentDto
 */
export interface CreateStablePaymentIntentDto {
    /**
     * The stablecoin currency to convert FROM. This is the currency the customer will pay with.
     * @type {StableCoinCurrency}
     * @memberof CreateStablePaymentIntentDto
     */
    sourceCurrency: StableCoinCurrency;
    /**
     * The blockchain network where the source currency resides. Determines gas fees and transaction speed.
     * @type {BridgePaymentRail}
     * @memberof CreateStablePaymentIntentDto
     */
    sourceNetwork: BridgePaymentRail;
    /**
     * The stablecoin currency to convert TO. If omitted, defaults to the same as source currency (cross-chain transfer).
     * @type {StableCoinCurrency}
     * @memberof CreateStablePaymentIntentDto
     */
    destinationCurrency?: StableCoinCurrency;
    /**
     * The blockchain network where the converted currency will be delivered. Must support the destination currency.
     * @type {BridgePaymentRail}
     * @memberof CreateStablePaymentIntentDto
     */
    destinationNetwork: BridgePaymentRail;
    /**
     * The wallet address where converted funds will be sent. Supports Ethereum (0x...) and Solana address formats.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    destinationAddress?: string;
    /**
     * Payment amount in the source currency. Omit for flexible amount payments where users specify the amount during checkout.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    amount?: string;
    /**
     * Customer's first name. Used for transaction records and compliance. Required for amounts over $1000.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerFirstName?: string;
    /**
     * Customer's last name. Used for transaction records and compliance. Required for amounts over $1000.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerLastName?: string;
    /**
     * Customer's email address. Used for transaction notifications and receipts. Highly recommended for all transactions.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerEmail?: string;
    /**
     * Customer's full address. Required for compliance in certain jurisdictions and high-value transactions.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerAddress?: string;
    /**
     * Customer's country of residence. Used for compliance and tax reporting.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerCountry?: string;
    /**
     * Customer's country ISO 3166-1 alpha-2 code. Used for automated compliance checks.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerCountryISO?: string;
    /**
     * Customer's state or province. Required for US and Canadian customers.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerProvince?: string;
    /**
     * Customer's state or province ISO code. Used for automated tax calculations.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    customerProvinceISO?: string;
    /**
     * Customer's phone number with country code. Used for SMS notifications and verification.
     * @type {string}
     * @memberof CreateStablePaymentIntentDto
     */
    phoneNumber?: string;
}



/**
 * Check if a given object implements the CreateStablePaymentIntentDto interface.
 */
export function instanceOfCreateStablePaymentIntentDto(value: object): value is CreateStablePaymentIntentDto {
    if (!('sourceCurrency' in value) || value['sourceCurrency'] === undefined) return false;
    if (!('sourceNetwork' in value) || value['sourceNetwork'] === undefined) return false;
    if (!('destinationNetwork' in value) || value['destinationNetwork'] === undefined) return false;
    return true;
}

export function CreateStablePaymentIntentDtoFromJSON(json: any): CreateStablePaymentIntentDto {
    return CreateStablePaymentIntentDtoFromJSONTyped(json, false);
}

export function CreateStablePaymentIntentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStablePaymentIntentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceCurrency': StableCoinCurrencyFromJSON(json['sourceCurrency']),
        'sourceNetwork': BridgePaymentRailFromJSON(json['sourceNetwork']),
        'destinationCurrency': json['destinationCurrency'] == null ? undefined : StableCoinCurrencyFromJSON(json['destinationCurrency']),
        'destinationNetwork': BridgePaymentRailFromJSON(json['destinationNetwork']),
        'destinationAddress': json['destinationAddress'] == null ? undefined : json['destinationAddress'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'customerFirstName': json['customer_first_name'] == null ? undefined : json['customer_first_name'],
        'customerLastName': json['customer_last_name'] == null ? undefined : json['customer_last_name'],
        'customerEmail': json['customer_email'] == null ? undefined : json['customer_email'],
        'customerAddress': json['customer_address'] == null ? undefined : json['customer_address'],
        'customerCountry': json['customer_country'] == null ? undefined : json['customer_country'],
        'customerCountryISO': json['customer_countryISO'] == null ? undefined : json['customer_countryISO'],
        'customerProvince': json['customer_province'] == null ? undefined : json['customer_province'],
        'customerProvinceISO': json['customer_provinceISO'] == null ? undefined : json['customer_provinceISO'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
    };
}

export function CreateStablePaymentIntentDtoToJSON(json: any): CreateStablePaymentIntentDto {
    return CreateStablePaymentIntentDtoToJSONTyped(json, false);
}

export function CreateStablePaymentIntentDtoToJSONTyped(value?: CreateStablePaymentIntentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sourceCurrency': StableCoinCurrencyToJSON(value['sourceCurrency']),
        'sourceNetwork': BridgePaymentRailToJSON(value['sourceNetwork']),
        'destinationCurrency': StableCoinCurrencyToJSON(value['destinationCurrency']),
        'destinationNetwork': BridgePaymentRailToJSON(value['destinationNetwork']),
        'destinationAddress': value['destinationAddress'],
        'amount': value['amount'],
        'customer_first_name': value['customerFirstName'],
        'customer_last_name': value['customerLastName'],
        'customer_email': value['customerEmail'],
        'customer_address': value['customerAddress'],
        'customer_country': value['customerCountry'],
        'customer_countryISO': value['customerCountryISO'],
        'customer_province': value['customerProvince'],
        'customer_provinceISO': value['customerProvinceISO'],
        'phoneNumber': value['phoneNumber'],
    };
}

