/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookDto
 */
export interface CreateWebhookDto {
    /**
     * Name of the webhook for identification purposes
     * @type {string}
     * @memberof CreateWebhookDto
     */
    name: string;
    /**
     * URL where webhook events will be sent
     * @type {string}
     * @memberof CreateWebhookDto
     */
    url: string;
    /**
     * Whether the webhook is active and will receive events
     * @type {boolean}
     * @memberof CreateWebhookDto
     */
    isActive: boolean;
    /**
     * Secret key used to sign webhook payloads for verification
     * @type {string}
     * @memberof CreateWebhookDto
     */
    signingSecret?: string;
    /**
     * Whether webhook payloads should be encrypted
     * @type {boolean}
     * @memberof CreateWebhookDto
     */
    encrypted: boolean;
}

/**
 * Check if a given object implements the CreateWebhookDto interface.
 */
export function instanceOfCreateWebhookDto(value: object): value is CreateWebhookDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('encrypted' in value) || value['encrypted'] === undefined) return false;
    return true;
}

export function CreateWebhookDtoFromJSON(json: any): CreateWebhookDto {
    return CreateWebhookDtoFromJSONTyped(json, false);
}

export function CreateWebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'isActive': json['isActive'],
        'signingSecret': json['signing_secret'] == null ? undefined : json['signing_secret'],
        'encrypted': json['encrypted'],
    };
}

export function CreateWebhookDtoToJSON(json: any): CreateWebhookDto {
    return CreateWebhookDtoToJSONTyped(json, false);
}

export function CreateWebhookDtoToJSONTyped(value?: CreateWebhookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'isActive': value['isActive'],
        'signing_secret': value['signingSecret'],
        'encrypted': value['encrypted'],
    };
}

