/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDirectBankTransferDto
 */
export interface CreateDirectBankTransferDto {
    /**
     * The ID of the bridge wallet to transfer from
     * @type {string}
     * @memberof CreateDirectBankTransferDto
     */
    walletId: string;
    /**
     * The payment rail to use
     * @type {string}
     * @memberof CreateDirectBankTransferDto
     */
    paymentRail: string;
    /**
     * The destination currency
     * @type {string}
     * @memberof CreateDirectBankTransferDto
     */
    destinationCurrency: string;
    /**
     * The source currency
     * @type {string}
     * @memberof CreateDirectBankTransferDto
     */
    sourceCurrency: string;
    /**
     * The amount to transfer
     * @type {number}
     * @memberof CreateDirectBankTransferDto
     */
    amount: number;
    /**
     * Wire transfer message
     * @type {string}
     * @memberof CreateDirectBankTransferDto
     */
    wireMessage?: string;
    /**
     * SEPA transfer reference
     * @type {string}
     * @memberof CreateDirectBankTransferDto
     */
    sepaReference?: string;
    /**
     * ACH transfer reference
     * @type {string}
     * @memberof CreateDirectBankTransferDto
     */
    achReference?: string;
}

/**
 * Check if a given object implements the CreateDirectBankTransferDto interface.
 */
export function instanceOfCreateDirectBankTransferDto(value: object): value is CreateDirectBankTransferDto {
    if (!('walletId' in value) || value['walletId'] === undefined) return false;
    if (!('paymentRail' in value) || value['paymentRail'] === undefined) return false;
    if (!('destinationCurrency' in value) || value['destinationCurrency'] === undefined) return false;
    if (!('sourceCurrency' in value) || value['sourceCurrency'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateDirectBankTransferDtoFromJSON(json: any): CreateDirectBankTransferDto {
    return CreateDirectBankTransferDtoFromJSONTyped(json, false);
}

export function CreateDirectBankTransferDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDirectBankTransferDto {
    if (json == null) {
        return json;
    }
    return {
        
        'walletId': json['walletId'],
        'paymentRail': json['paymentRail'],
        'destinationCurrency': json['destinationCurrency'],
        'sourceCurrency': json['sourceCurrency'],
        'amount': json['amount'],
        'wireMessage': json['wire_message'] == null ? undefined : json['wire_message'],
        'sepaReference': json['sepa_reference'] == null ? undefined : json['sepa_reference'],
        'achReference': json['ach_reference'] == null ? undefined : json['ach_reference'],
    };
}

export function CreateDirectBankTransferDtoToJSON(json: any): CreateDirectBankTransferDto {
    return CreateDirectBankTransferDtoToJSONTyped(json, false);
}

export function CreateDirectBankTransferDtoToJSONTyped(value?: CreateDirectBankTransferDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'walletId': value['walletId'],
        'paymentRail': value['paymentRail'],
        'destinationCurrency': value['destinationCurrency'],
        'sourceCurrency': value['sourceCurrency'],
        'amount': value['amount'],
        'wire_message': value['wireMessage'],
        'sepa_reference': value['sepaReference'],
        'ach_reference': value['achReference'],
    };
}

