/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of customer account. Determines available features and compliance requirements.
 * @export
 */
export const CustomerType = {
    Individual: 'Individual',
    Startup: 'Startup',
    SmallBusiness: 'Small Business',
    MediumBusiness: 'Medium Business',
    Enterprise: 'Enterprise',
    NonProfit: 'Non-Profit',
    Government: 'Government'
} as const;
export type CustomerType = typeof CustomerType[keyof typeof CustomerType];


export function instanceOfCustomerType(value: any): boolean {
    for (const key in CustomerType) {
        if (Object.prototype.hasOwnProperty.call(CustomerType, key)) {
            if (CustomerType[key as keyof typeof CustomerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CustomerTypeFromJSON(json: any): CustomerType {
    return CustomerTypeFromJSONTyped(json, false);
}

export function CustomerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerType {
    return json as CustomerType;
}

export function CustomerTypeToJSON(value?: CustomerType | null): any {
    return value as any;
}

export function CustomerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CustomerType {
    return value as CustomerType;
}

