/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Current status of the customer account. Controls access to services and features.
 * @export
 */
export const CustomerStatus = {
    Active: 'ACTIVE',
    Blacklisted: 'BLACKLISTED',
    Deactivated: 'DEACTIVATED',
    Deleted: 'DELETED'
} as const;
export type CustomerStatus = typeof CustomerStatus[keyof typeof CustomerStatus];


export function instanceOfCustomerStatus(value: any): boolean {
    for (const key in CustomerStatus) {
        if (Object.prototype.hasOwnProperty.call(CustomerStatus, key)) {
            if (CustomerStatus[key as keyof typeof CustomerStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CustomerStatusFromJSON(json: any): CustomerStatus {
    return CustomerStatusFromJSONTyped(json, false);
}

export function CustomerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerStatus {
    return json as CustomerStatus;
}

export function CustomerStatusToJSON(value?: CustomerStatus | null): any {
    return value as any;
}

export function CustomerStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): CustomerStatus {
    return value as CustomerStatus;
}

