/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Currency for sending funds
 * @export
 */
export const DestinationCurrency = {
    Usd: 'usd',
    Eur: 'eur',
    Mxn: 'mxn',
    Usdc: 'usdc',
    Eurc: 'eurc',
    Dai: 'dai',
    Pyusd: 'pyusd',
    Usdt: 'usdt'
} as const;
export type DestinationCurrency = typeof DestinationCurrency[keyof typeof DestinationCurrency];


export function instanceOfDestinationCurrency(value: any): boolean {
    for (const key in DestinationCurrency) {
        if (Object.prototype.hasOwnProperty.call(DestinationCurrency, key)) {
            if (DestinationCurrency[key as keyof typeof DestinationCurrency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DestinationCurrencyFromJSON(json: any): DestinationCurrency {
    return DestinationCurrencyFromJSONTyped(json, false);
}

export function DestinationCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationCurrency {
    return json as DestinationCurrency;
}

export function DestinationCurrencyToJSON(value?: DestinationCurrency | null): any {
    return value as any;
}

export function DestinationCurrencyToJSONTyped(value: any, ignoreDiscriminator: boolean): DestinationCurrency {
    return value as DestinationCurrency;
}

