/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeRateResponseDto
 */
export interface ExchangeRateResponseDto {
    /**
     * Source currency code (USD for USDC)
     * @type {string}
     * @memberof ExchangeRateResponseDto
     */
    from: string;
    /**
     * Target currency code (EUR for EURC)
     * @type {string}
     * @memberof ExchangeRateResponseDto
     */
    to: string;
    /**
     * Mid-market exchange rate from source to target currency
     * @type {string}
     * @memberof ExchangeRateResponseDto
     */
    midmarketRate: string;
    /**
     * Rate for buying target currency (what you get when converting from source to target)
     * @type {string}
     * @memberof ExchangeRateResponseDto
     */
    buyRate: string;
    /**
     * Rate for selling target currency (what you pay when converting from target to source)
     * @type {string}
     * @memberof ExchangeRateResponseDto
     */
    sellRate: string;
    /**
     * Timestamp when the exchange rate was last updated
     * @type {string}
     * @memberof ExchangeRateResponseDto
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the ExchangeRateResponseDto interface.
 */
export function instanceOfExchangeRateResponseDto(value: object): value is ExchangeRateResponseDto {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('midmarketRate' in value) || value['midmarketRate'] === undefined) return false;
    if (!('buyRate' in value) || value['buyRate'] === undefined) return false;
    if (!('sellRate' in value) || value['sellRate'] === undefined) return false;
    return true;
}

export function ExchangeRateResponseDtoFromJSON(json: any): ExchangeRateResponseDto {
    return ExchangeRateResponseDtoFromJSONTyped(json, false);
}

export function ExchangeRateResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeRateResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'midmarketRate': json['midmarket_rate'],
        'buyRate': json['buy_rate'],
        'sellRate': json['sell_rate'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function ExchangeRateResponseDtoToJSON(json: any): ExchangeRateResponseDto {
    return ExchangeRateResponseDtoToJSONTyped(json, false);
}

export function ExchangeRateResponseDtoToJSONTyped(value?: ExchangeRateResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
        'midmarket_rate': value['midmarketRate'],
        'buy_rate': value['buyRate'],
        'sell_rate': value['sellRate'],
        'timestamp': value['timestamp'],
    };
}

