/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The fiat currency to convert FROM. Must match the currency of the source payment rail.
 * @export
 */
export const FiatCurrency = {
    Usd: 'usd',
    Eur: 'eur',
    Mxn: 'mxn'
} as const;
export type FiatCurrency = typeof FiatCurrency[keyof typeof FiatCurrency];


export function instanceOfFiatCurrency(value: any): boolean {
    for (const key in FiatCurrency) {
        if (Object.prototype.hasOwnProperty.call(FiatCurrency, key)) {
            if (FiatCurrency[key as keyof typeof FiatCurrency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FiatCurrencyFromJSON(json: any): FiatCurrency {
    return FiatCurrencyFromJSONTyped(json, false);
}

export function FiatCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiatCurrency {
    return json as FiatCurrency;
}

export function FiatCurrencyToJSON(value?: FiatCurrency | null): any {
    return value as any;
}

export function FiatCurrencyToJSONTyped(value: any, ignoreDiscriminator: boolean): FiatCurrency {
    return value as FiatCurrency;
}

