/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthResponseDto
 */
export interface HealthResponseDto {
    /**
     * Overall health status of the service. Returns "ok" when healthy, "error" when issues detected.
     * @type {string}
     * @memberof HealthResponseDto
     */
    status: HealthResponseDtoStatusEnum;
    /**
     * ISO 8601 timestamp when the health check was performed.
     * @type {Date}
     * @memberof HealthResponseDto
     */
    timestamp: Date;
    /**
     * Current version of the API service. Useful for debugging and compatibility checks.
     * @type {string}
     * @memberof HealthResponseDto
     */
    version: string;
    /**
     * Database connectivity status. Shows "connected" when database is accessible, "error" when connection fails.
     * @type {string}
     * @memberof HealthResponseDto
     */
    database: HealthResponseDtoDatabaseEnum;
    /**
     * Human-readable message describing the current health status and any issues.
     * @type {string}
     * @memberof HealthResponseDto
     */
    message: string;
    /**
     * Indicates whether the request was properly authenticated. Always true for this endpoint since authentication is required.
     * @type {boolean}
     * @memberof HealthResponseDto
     */
    authenticated: boolean;
}


/**
 * @export
 */
export const HealthResponseDtoStatusEnum = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type HealthResponseDtoStatusEnum = typeof HealthResponseDtoStatusEnum[keyof typeof HealthResponseDtoStatusEnum];

/**
 * @export
 */
export const HealthResponseDtoDatabaseEnum = {
    Connected: 'connected',
    Error: 'error'
} as const;
export type HealthResponseDtoDatabaseEnum = typeof HealthResponseDtoDatabaseEnum[keyof typeof HealthResponseDtoDatabaseEnum];


/**
 * Check if a given object implements the HealthResponseDto interface.
 */
export function instanceOfHealthResponseDto(value: object): value is HealthResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('database' in value) || value['database'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('authenticated' in value) || value['authenticated'] === undefined) return false;
    return true;
}

export function HealthResponseDtoFromJSON(json: any): HealthResponseDto {
    return HealthResponseDtoFromJSONTyped(json, false);
}

export function HealthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': (new Date(json['timestamp'])),
        'version': json['version'],
        'database': json['database'],
        'message': json['message'],
        'authenticated': json['authenticated'],
    };
}

export function HealthResponseDtoToJSON(json: any): HealthResponseDto {
    return HealthResponseDtoToJSONTyped(json, false);
}

export function HealthResponseDtoToJSONTyped(value?: HealthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'].toISOString(),
        'version': value['version'],
        'database': value['database'],
        'message': value['message'],
        'authenticated': value['authenticated'],
    };
}

