/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceProductDto
 */
export interface InvoiceProductDto {
    /**
     * Product ID
     * @type {string}
     * @memberof InvoiceProductDto
     */
    productId: string;
    /**
     * Quantity of the product
     * @type {number}
     * @memberof InvoiceProductDto
     */
    quantity: number;
}

/**
 * Check if a given object implements the InvoiceProductDto interface.
 */
export function instanceOfInvoiceProductDto(value: object): value is InvoiceProductDto {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function InvoiceProductDtoFromJSON(json: any): InvoiceProductDto {
    return InvoiceProductDtoFromJSONTyped(json, false);
}

export function InvoiceProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['product_id'],
        'quantity': json['quantity'],
    };
}

export function InvoiceProductDtoToJSON(json: any): InvoiceProductDto {
    return InvoiceProductDtoToJSONTyped(json, false);
}

export function InvoiceProductDtoToJSONTyped(value?: InvoiceProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_id': value['productId'],
        'quantity': value['quantity'],
    };
}

