/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LiquidationAddressResponseDto
 */
export interface LiquidationAddressResponseDto {
    /**
     * Unique identifier for the liquidation address
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    id: string;
    /**
     * Current state of the liquidation address
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    state: string;
    /**
     * Customer ID this liquidation address belongs to
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    customerId: string;
    /**
     * Blockchain chain
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    chain: string;
    /**
     * Currency
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    currency: string;
    /**
     * Liquidation address
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    address: string;
    /**
     * External account ID
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    externalAccountId?: string;
    /**
     * Prefunded account ID
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    prefundedAccountId?: string;
    /**
     * Bridge wallet ID
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    bridgeWalletId?: string;
    /**
     * Destination payment rail
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    destinationPaymentRail?: string;
    /**
     * Destination currency
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    destinationCurrency?: string;
    /**
     * Custom developer fee percent
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    customDeveloperFeePercent?: string;
    /**
     * Creation timestamp
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    createdAt: string;
    /**
     * Last update timestamp
     * @type {string}
     * @memberof LiquidationAddressResponseDto
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the LiquidationAddressResponseDto interface.
 */
export function instanceOfLiquidationAddressResponseDto(value: object): value is LiquidationAddressResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('chain' in value) || value['chain'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function LiquidationAddressResponseDtoFromJSON(json: any): LiquidationAddressResponseDto {
    return LiquidationAddressResponseDtoFromJSONTyped(json, false);
}

export function LiquidationAddressResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiquidationAddressResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'state': json['state'],
        'customerId': json['customer_id'],
        'chain': json['chain'],
        'currency': json['currency'],
        'address': json['address'],
        'externalAccountId': json['external_account_id'] == null ? undefined : json['external_account_id'],
        'prefundedAccountId': json['prefunded_account_id'] == null ? undefined : json['prefunded_account_id'],
        'bridgeWalletId': json['bridge_wallet_id'] == null ? undefined : json['bridge_wallet_id'],
        'destinationPaymentRail': json['destination_payment_rail'] == null ? undefined : json['destination_payment_rail'],
        'destinationCurrency': json['destination_currency'] == null ? undefined : json['destination_currency'],
        'customDeveloperFeePercent': json['custom_developer_fee_percent'] == null ? undefined : json['custom_developer_fee_percent'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function LiquidationAddressResponseDtoToJSON(json: any): LiquidationAddressResponseDto {
    return LiquidationAddressResponseDtoToJSONTyped(json, false);
}

export function LiquidationAddressResponseDtoToJSONTyped(value?: LiquidationAddressResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'state': value['state'],
        'customer_id': value['customerId'],
        'chain': value['chain'],
        'currency': value['currency'],
        'address': value['address'],
        'external_account_id': value['externalAccountId'],
        'prefunded_account_id': value['prefundedAccountId'],
        'bridge_wallet_id': value['bridgeWalletId'],
        'destination_payment_rail': value['destinationPaymentRail'],
        'destination_currency': value['destinationCurrency'],
        'custom_developer_fee_percent': value['customDeveloperFeePercent'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

