/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentLinkProductDto
 */
export interface PaymentLinkProductDto {
    /**
     * UUID of the product to include in this payment link. Must be a valid product from your catalog.
     * @type {string}
     * @memberof PaymentLinkProductDto
     */
    productId: string;
    /**
     * Quantity of this product to include. Must be at least 1.
     * @type {number}
     * @memberof PaymentLinkProductDto
     */
    quantity: number;
}

/**
 * Check if a given object implements the PaymentLinkProductDto interface.
 */
export function instanceOfPaymentLinkProductDto(value: object): value is PaymentLinkProductDto {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function PaymentLinkProductDtoFromJSON(json: any): PaymentLinkProductDto {
    return PaymentLinkProductDtoFromJSONTyped(json, false);
}

export function PaymentLinkProductDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentLinkProductDto {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'quantity': json['quantity'],
    };
}

export function PaymentLinkProductDtoToJSON(json: any): PaymentLinkProductDto {
    return PaymentLinkProductDtoToJSONTyped(json, false);
}

export function PaymentLinkProductDtoToJSONTyped(value?: PaymentLinkProductDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'quantity': value['quantity'],
    };
}

