/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentRequestDto
 */
export interface PaymentRequestDto {
    /**
     * The amount to charge
     * @type {number}
     * @memberof PaymentRequestDto
     */
    amount: number;
    /**
     * The currency code
     * @type {string}
     * @memberof PaymentRequestDto
     */
    currency: string;
    /**
     * Description of the payment
     * @type {string}
     * @memberof PaymentRequestDto
     */
    description: string;
    /**
     * Customer reference ID
     * @type {string}
     * @memberof PaymentRequestDto
     */
    customerId?: string;
}

/**
 * Check if a given object implements the PaymentRequestDto interface.
 */
export function instanceOfPaymentRequestDto(value: object): value is PaymentRequestDto {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function PaymentRequestDtoFromJSON(json: any): PaymentRequestDto {
    return PaymentRequestDtoFromJSONTyped(json, false);
}

export function PaymentRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'currency': json['currency'],
        'description': json['description'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
    };
}

export function PaymentRequestDtoToJSON(json: any): PaymentRequestDto {
    return PaymentRequestDtoToJSONTyped(json, false);
}

export function PaymentRequestDtoToJSONTyped(value?: PaymentRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'currency': value['currency'],
        'description': value['description'],
        'customerId': value['customerId'],
    };
}

