/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentResponseDto
 */
export interface PaymentResponseDto {
    /**
     * Payment ID
     * @type {string}
     * @memberof PaymentResponseDto
     */
    id: string;
    /**
     * The amount charged
     * @type {number}
     * @memberof PaymentResponseDto
     */
    amount: number;
    /**
     * The currency code
     * @type {string}
     * @memberof PaymentResponseDto
     */
    currency: string;
    /**
     * Payment status
     * @type {string}
     * @memberof PaymentResponseDto
     */
    status: string;
    /**
     * Timestamp of the payment
     * @type {string}
     * @memberof PaymentResponseDto
     */
    timestamp: string;
}

/**
 * Check if a given object implements the PaymentResponseDto interface.
 */
export function instanceOfPaymentResponseDto(value: object): value is PaymentResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PaymentResponseDtoFromJSON(json: any): PaymentResponseDto {
    return PaymentResponseDtoFromJSONTyped(json, false);
}

export function PaymentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'currency': json['currency'],
        'status': json['status'],
        'timestamp': json['timestamp'],
    };
}

export function PaymentResponseDtoToJSON(json: any): PaymentResponseDto {
    return PaymentResponseDtoToJSONTyped(json, false);
}

export function PaymentResponseDtoToJSONTyped(value?: PaymentResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'currency': value['currency'],
        'status': value['status'],
        'timestamp': value['timestamp'],
    };
}

