/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicHealthResponseDto
 */
export interface PublicHealthResponseDto {
    /**
     * Basic health status of the service. Returns "ok" when the service is responding.
     * @type {string}
     * @memberof PublicHealthResponseDto
     */
    status: PublicHealthResponseDtoStatusEnum;
    /**
     * ISO 8601 timestamp when the health check was performed.
     * @type {Date}
     * @memberof PublicHealthResponseDto
     */
    timestamp: Date;
    /**
     * Current version of the API service.
     * @type {string}
     * @memberof PublicHealthResponseDto
     */
    version: string;
}


/**
 * @export
 */
export const PublicHealthResponseDtoStatusEnum = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type PublicHealthResponseDtoStatusEnum = typeof PublicHealthResponseDtoStatusEnum[keyof typeof PublicHealthResponseDtoStatusEnum];


/**
 * Check if a given object implements the PublicHealthResponseDto interface.
 */
export function instanceOfPublicHealthResponseDto(value: object): value is PublicHealthResponseDto {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PublicHealthResponseDtoFromJSON(json: any): PublicHealthResponseDto {
    return PublicHealthResponseDtoFromJSONTyped(json, false);
}

export function PublicHealthResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicHealthResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'timestamp': (new Date(json['timestamp'])),
        'version': json['version'],
    };
}

export function PublicHealthResponseDtoToJSON(json: any): PublicHealthResponseDto {
    return PublicHealthResponseDtoToJSONTyped(json, false);
}

export function PublicHealthResponseDtoToJSONTyped(value?: PublicHealthResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'timestamp': value['timestamp'].toISOString(),
        'version': value['version'],
    };
}

