/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefundResponseDto
 */
export interface RefundResponseDto {
    /**
     * Refund ID
     * @type {string}
     * @memberof RefundResponseDto
     */
    id: string;
    /**
     * Original payment ID
     * @type {string}
     * @memberof RefundResponseDto
     */
    paymentId: string;
    /**
     * The amount refunded
     * @type {number}
     * @memberof RefundResponseDto
     */
    amount: number;
    /**
     * Refund status
     * @type {string}
     * @memberof RefundResponseDto
     */
    status: string;
    /**
     * Timestamp of the refund
     * @type {string}
     * @memberof RefundResponseDto
     */
    timestamp: string;
}

/**
 * Check if a given object implements the RefundResponseDto interface.
 */
export function instanceOfRefundResponseDto(value: object): value is RefundResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function RefundResponseDtoFromJSON(json: any): RefundResponseDto {
    return RefundResponseDtoFromJSONTyped(json, false);
}

export function RefundResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'paymentId': json['paymentId'],
        'amount': json['amount'],
        'status': json['status'],
        'timestamp': json['timestamp'],
    };
}

export function RefundResponseDtoToJSON(json: any): RefundResponseDto {
    return RefundResponseDtoToJSONTyped(json, false);
}

export function RefundResponseDtoToJSONTyped(value?: RefundResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'paymentId': value['paymentId'],
        'amount': value['amount'],
        'status': value['status'],
        'timestamp': value['timestamp'],
    };
}

