/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The stablecoin currency to convert FROM. This is the currency the customer will pay with.
 * @export
 */
export const StableCoinCurrency = {
    Usdc: 'usdc',
    Eurc: 'eurc'
} as const;
export type StableCoinCurrency = typeof StableCoinCurrency[keyof typeof StableCoinCurrency];


export function instanceOfStableCoinCurrency(value: any): boolean {
    for (const key in StableCoinCurrency) {
        if (Object.prototype.hasOwnProperty.call(StableCoinCurrency, key)) {
            if (StableCoinCurrency[key as keyof typeof StableCoinCurrency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StableCoinCurrencyFromJSON(json: any): StableCoinCurrency {
    return StableCoinCurrencyFromJSONTyped(json, false);
}

export function StableCoinCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StableCoinCurrency {
    return json as StableCoinCurrency;
}

export function StableCoinCurrencyToJSON(value?: StableCoinCurrency | null): any {
    return value as any;
}

export function StableCoinCurrencyToJSONTyped(value: any, ignoreDiscriminator: boolean): StableCoinCurrency {
    return value as StableCoinCurrency;
}

