/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxControllerCreate201Response
 */
export interface TaxControllerCreate201Response {
    /**
     * 
     * @type {string}
     * @memberof TaxControllerCreate201Response
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TaxControllerCreate201Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TaxControllerCreate201Response
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof TaxControllerCreate201Response
     */
    percentage?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TaxControllerCreate201Response
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof TaxControllerCreate201Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof TaxControllerCreate201Response
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the TaxControllerCreate201Response interface.
 */
export function instanceOfTaxControllerCreate201Response(value: object): value is TaxControllerCreate201Response {
    return true;
}

export function TaxControllerCreate201ResponseFromJSON(json: any): TaxControllerCreate201Response {
    return TaxControllerCreate201ResponseFromJSONTyped(json, false);
}

export function TaxControllerCreate201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxControllerCreate201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function TaxControllerCreate201ResponseToJSON(json: any): TaxControllerCreate201Response {
    return TaxControllerCreate201ResponseToJSONTyped(json, false);
}

export function TaxControllerCreate201ResponseToJSONTyped(value?: TaxControllerCreate201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'percentage': value['percentage'],
        'active': value['active'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

