/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxControllerDeleteWithoutId400Response
 */
export interface TaxControllerDeleteWithoutId400Response {
    /**
     * 
     * @type {string}
     * @memberof TaxControllerDeleteWithoutId400Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TaxControllerDeleteWithoutId400Response
     */
    error?: string;
    /**
     * 
     * @type {number}
     * @memberof TaxControllerDeleteWithoutId400Response
     */
    statusCode?: number;
}

/**
 * Check if a given object implements the TaxControllerDeleteWithoutId400Response interface.
 */
export function instanceOfTaxControllerDeleteWithoutId400Response(value: object): value is TaxControllerDeleteWithoutId400Response {
    return true;
}

export function TaxControllerDeleteWithoutId400ResponseFromJSON(json: any): TaxControllerDeleteWithoutId400Response {
    return TaxControllerDeleteWithoutId400ResponseFromJSONTyped(json, false);
}

export function TaxControllerDeleteWithoutId400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxControllerDeleteWithoutId400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
    };
}

export function TaxControllerDeleteWithoutId400ResponseToJSON(json: any): TaxControllerDeleteWithoutId400Response {
    return TaxControllerDeleteWithoutId400ResponseToJSONTyped(json, false);
}

export function TaxControllerDeleteWithoutId400ResponseToJSONTyped(value?: TaxControllerDeleteWithoutId400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
    };
}

