/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxControllerUpdateWithoutId400Response
 */
export interface TaxControllerUpdateWithoutId400Response {
    /**
     * 
     * @type {string}
     * @memberof TaxControllerUpdateWithoutId400Response
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TaxControllerUpdateWithoutId400Response
     */
    error?: string;
    /**
     * 
     * @type {number}
     * @memberof TaxControllerUpdateWithoutId400Response
     */
    statusCode?: number;
}

/**
 * Check if a given object implements the TaxControllerUpdateWithoutId400Response interface.
 */
export function instanceOfTaxControllerUpdateWithoutId400Response(value: object): value is TaxControllerUpdateWithoutId400Response {
    return true;
}

export function TaxControllerUpdateWithoutId400ResponseFromJSON(json: any): TaxControllerUpdateWithoutId400Response {
    return TaxControllerUpdateWithoutId400ResponseFromJSONTyped(json, false);
}

export function TaxControllerUpdateWithoutId400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxControllerUpdateWithoutId400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
    };
}

export function TaxControllerUpdateWithoutId400ResponseToJSON(json: any): TaxControllerUpdateWithoutId400Response {
    return TaxControllerUpdateWithoutId400ResponseToJSONTyped(json, false);
}

export function TaxControllerUpdateWithoutId400ResponseToJSONTyped(value?: TaxControllerUpdateWithoutId400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'error': value['error'],
        'statusCode': value['statusCode'],
    };
}

