/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaxDto
 */
export interface UpdateTaxDto {
    /**
     * Tax name for identification and display purposes
     * @type {string}
     * @memberof UpdateTaxDto
     */
    name?: string;
    /**
     * Detailed description of what this tax covers
     * @type {string}
     * @memberof UpdateTaxDto
     */
    description?: string;
    /**
     * Tax rate as a percentage (0-100)
     * @type {number}
     * @memberof UpdateTaxDto
     */
    percentage?: number;
    /**
     * Whether this tax is currently active and can be applied
     * @type {boolean}
     * @memberof UpdateTaxDto
     */
    active?: boolean;
    /**
     * Array of app IDs where this tax should be available
     * @type {Array<string>}
     * @memberof UpdateTaxDto
     */
    appIds?: Array<string>;
}

/**
 * Check if a given object implements the UpdateTaxDto interface.
 */
export function instanceOfUpdateTaxDto(value: object): value is UpdateTaxDto {
    return true;
}

export function UpdateTaxDtoFromJSON(json: any): UpdateTaxDto {
    return UpdateTaxDtoFromJSONTyped(json, false);
}

export function UpdateTaxDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaxDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'percentage': json['percentage'] == null ? undefined : json['percentage'],
        'active': json['active'] == null ? undefined : json['active'],
        'appIds': json['appIds'] == null ? undefined : json['appIds'],
    };
}

export function UpdateTaxDtoToJSON(json: any): UpdateTaxDto {
    return UpdateTaxDtoToJSONTyped(json, false);
}

export function UpdateTaxDtoToJSONTyped(value?: UpdateTaxDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'percentage': value['percentage'],
        'active': value['active'],
        'appIds': value['appIds'],
    };
}

