/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerStatus } from './CustomerStatus';
import {
    CustomerStatusFromJSON,
    CustomerStatusFromJSONTyped,
    CustomerStatusToJSON,
    CustomerStatusToJSONTyped,
} from './CustomerStatus';
import type { CustomerType } from './CustomerType';
import {
    CustomerTypeFromJSON,
    CustomerTypeFromJSONTyped,
    CustomerTypeToJSON,
    CustomerTypeToJSONTyped,
} from './CustomerType';

/**
 * 
 * @export
 * @interface UpdateCustomerDto
 */
export interface UpdateCustomerDto {
    /**
     * Customer's first name. Used for personalization and legal documentation.
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    firstName?: string;
    /**
     * Customer's last name. Used for personalization and legal documentation.
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    lastName?: string;
    /**
     * Customer's email address. Used for notifications, receipts, and account management. Must be a valid email format.
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    email?: string;
    /**
     * Customer's phone number. Used for SMS notifications and verification. Include country code for international numbers.
     * @type {string}
     * @memberof UpdateCustomerDto
     */
    phoneNumber?: string;
    /**
     * Type of customer account. Determines available features and compliance requirements.
     * @type {CustomerType}
     * @memberof UpdateCustomerDto
     */
    customerType?: CustomerType;
    /**
     * Current status of the customer account. Controls access to services and features.
     * @type {CustomerStatus}
     * @memberof UpdateCustomerDto
     */
    status?: CustomerStatus;
}



/**
 * Check if a given object implements the UpdateCustomerDto interface.
 */
export function instanceOfUpdateCustomerDto(value: object): value is UpdateCustomerDto {
    return true;
}

export function UpdateCustomerDtoFromJSON(json: any): UpdateCustomerDto {
    return UpdateCustomerDtoFromJSONTyped(json, false);
}

export function UpdateCustomerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phoneNumber': json['phone_number'] == null ? undefined : json['phone_number'],
        'customerType': json['customer_type'] == null ? undefined : CustomerTypeFromJSON(json['customer_type']),
        'status': json['status'] == null ? undefined : CustomerStatusFromJSON(json['status']),
    };
}

export function UpdateCustomerDtoToJSON(json: any): UpdateCustomerDto {
    return UpdateCustomerDtoToJSONTyped(json, false);
}

export function UpdateCustomerDtoToJSONTyped(value?: UpdateCustomerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone_number': value['phoneNumber'],
        'customer_type': CustomerTypeToJSON(value['customerType']),
        'status': CustomerStatusToJSON(value['status']),
    };
}

