/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWebhookDto
 */
export interface UpdateWebhookDto {
    /**
     * Name of the webhook for identification purposes
     * @type {string}
     * @memberof UpdateWebhookDto
     */
    name?: string;
    /**
     * URL where webhook events will be sent
     * @type {string}
     * @memberof UpdateWebhookDto
     */
    url?: string;
    /**
     * Whether the webhook is active and will receive events
     * @type {boolean}
     * @memberof UpdateWebhookDto
     */
    isActive?: boolean;
    /**
     * Secret key used to sign webhook payloads for verification
     * @type {string}
     * @memberof UpdateWebhookDto
     */
    signingSecret?: string;
    /**
     * Whether webhook payloads should be encrypted
     * @type {boolean}
     * @memberof UpdateWebhookDto
     */
    encrypted?: boolean;
}

/**
 * Check if a given object implements the UpdateWebhookDto interface.
 */
export function instanceOfUpdateWebhookDto(value: object): value is UpdateWebhookDto {
    return true;
}

export function UpdateWebhookDtoFromJSON(json: any): UpdateWebhookDto {
    return UpdateWebhookDtoFromJSONTyped(json, false);
}

export function UpdateWebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebhookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'signingSecret': json['signing_secret'] == null ? undefined : json['signing_secret'],
        'encrypted': json['encrypted'] == null ? undefined : json['encrypted'],
    };
}

export function UpdateWebhookDtoToJSON(json: any): UpdateWebhookDto {
    return UpdateWebhookDtoToJSONTyped(json, false);
}

export function UpdateWebhookDtoToJSONTyped(value?: UpdateWebhookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'isActive': value['isActive'],
        'signing_secret': value['signingSecret'],
        'encrypted': value['encrypted'],
    };
}

