/* tslint:disable */
/* eslint-disable */
/**
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookResponseDto
 */
export interface WebhookResponseDto {
    /**
     * Unique identifier for the webhook
     * @type {string}
     * @memberof WebhookResponseDto
     */
    id: string;
    /**
     * Name of the webhook
     * @type {string}
     * @memberof WebhookResponseDto
     */
    name: string;
    /**
     * URL where webhook events are sent
     * @type {string}
     * @memberof WebhookResponseDto
     */
    url: string;
    /**
     * Whether the webhook is currently active
     * @type {boolean}
     * @memberof WebhookResponseDto
     */
    isActive: boolean;
    /**
     * Whether webhook payloads are encrypted
     * @type {boolean}
     * @memberof WebhookResponseDto
     */
    encrypted: boolean;
    /**
     * Timestamp when the webhook was created
     * @type {string}
     * @memberof WebhookResponseDto
     */
    createdAt: string;
    /**
     * Timestamp when the webhook was last updated
     * @type {string}
     * @memberof WebhookResponseDto
     */
    updatedAt: string;
    /**
     * Webhook delivery statistics
     * @type {object}
     * @memberof WebhookResponseDto
     */
    deliveryStats: object;
}

/**
 * Check if a given object implements the WebhookResponseDto interface.
 */
export function instanceOfWebhookResponseDto(value: object): value is WebhookResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('encrypted' in value) || value['encrypted'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('deliveryStats' in value) || value['deliveryStats'] === undefined) return false;
    return true;
}

export function WebhookResponseDtoFromJSON(json: any): WebhookResponseDto {
    return WebhookResponseDtoFromJSONTyped(json, false);
}

export function WebhookResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'url': json['url'],
        'isActive': json['isActive'],
        'encrypted': json['encrypted'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'deliveryStats': json['delivery_stats'],
    };
}

export function WebhookResponseDtoToJSON(json: any): WebhookResponseDto {
    return WebhookResponseDtoToJSONTyped(json, false);
}

export function WebhookResponseDtoToJSONTyped(value?: WebhookResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url': value['url'],
        'isActive': value['isActive'],
        'encrypted': value['encrypted'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'delivery_stats': value['deliveryStats'],
    };
}

